import type { ApiSpec, Model, Enum, Service } from '../../ir/types.js';
import type { Emitter, EmitterContext, GeneratedFile } from '../../engine/types.js';
import { generateModels } from './models.js';
import { generateEnums } from './enums.js';
import { generateResources } from './resources.js';
import { generateClient } from './client.js';
import { generateErrors } from './errors.js';
import { generateConfig } from './config.js';
import { generateRbs } from './types-rbs.js';
import { generateRbi } from './types-rbi.js';
import { generateTests } from './tests.js';

export const rubyEmitter: Emitter = {
  language: 'ruby',

  generateModels(models: Model[], ctx: EmitterContext): GeneratedFile[] {
    return generateModels(models, ctx);
  },

  generateEnums(enums: Enum[], ctx: EmitterContext): GeneratedFile[] {
    return generateEnums(enums, ctx);
  },

  generateResources(services: Service[], ctx: EmitterContext): GeneratedFile[] {
    return generateResources(services, ctx);
  },

  generateClient(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return generateClient(spec, ctx);
  },

  generateErrors(ctx: EmitterContext): GeneratedFile[] {
    return generateErrors(ctx);
  },

  generateConfig(ctx: EmitterContext): GeneratedFile[] {
    return generateConfig(ctx);
  },

  generateTypeSignatures(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return [...generateRbs(spec, ctx), ...generateRbi(spec, ctx)];
  },

  generateTests(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return generateTests(spec, ctx);
  },

  fileHeader(): string {
    return '# frozen_string_literal: true\n# This file is auto-generated by oagen. Do not edit manually.';
  },
};
