// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Operations for the Organizations API.
public struct Organizations: Sendable {
    let transport: Transport

    /// Get an Organization
    ///
    /// - Parameter id: The unique ID of the Organization.
    public func getOrganization(
        id: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> Organization {
        let path = "organizations/\(id)"
        return try await transport.request(
            method: "GET",
            path: path,
            query: [],
            options: requestOptions,
            as: Organization.self
        )
    }

    /// List Organizations
    public func listOrganizations(
        limit: Int? = nil,
        before: String? = nil,
        domains: [String]? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> Page<Organization> {
        let path = "organizations"
        return try await transport.request(
            method: "GET",
            path: path,
            query: [("limit", limit), ("before", before)],
            options: requestOptions,
            as: Page<Organization>.self
        )
    }

    /// Create an Organization
    public func createOrganization(
        name: String,
        metadata: [String: AnyCodable]? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> Organization {
        let path = "organizations"
        var body = EncodableBody()
        body.set("name", name)
        body.set("metadata", metadata)
        return try await transport.request(
            method: "POST",
            path: path,
            query: [],
            body: body,
            options: requestOptions,
            as: Organization.self
        )
    }

    /// Delete an Organization
    public func deleteOrganization(
        id: String,
        requestOptions: RequestOptions? = nil
    ) async throws {
        let path = "organizations/\(id)"
        try await transport.requestVoid(
            method: "DELETE",
            path: path,
            options: requestOptions
        )
    }

    private func internalHelper() -> String {
        // A string with braces and slashes to exercise the scanner: {}/not-a-comment
        return "https://api.workos.com/{template}"
    }
}
