// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Operations for the Sso API.
public struct Sso: Sendable {
    let transport: Transport

    /// Get a Connection
    public func getConnection(
        id: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> Connection {
        let path = "connections/\(id)"
        return try await transport.request(
            method: "GET",
            path: path,
            query: [],
            options: requestOptions,
            as: Connection.self
        )
    }

    /// Build an authorization URL for the hosted SSO flow.
    public static func authorizationUrl(
        clientId: String,
        redirectUri: String
    ) -> String {
        return "https://api.workos.com/sso/authorize?client_id=\(clientId)&redirect_uri=\(redirectUri)"
    }

    /// Get a Profile
    public func getProfile(
        accessToken: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> Profile {
        let path = "sso/profile"
        return try await transport.request(
            method: "GET",
            path: path,
            query: [],
            options: requestOptions,
            as: Profile.self
        )
    }
}
