/**
 * SDK smoke test for workos-node.
 *
 * Calls the same endpoints via the generated workos-node SDK with fetch
 * interception to capture wire-level request/response pairs.
 *
 * Usage:
 *   OPENAPI_SPEC=path/to/spec.yaml npm run smoke:sdk:node -- --sdk-path path/to/workos-node
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { parseSpec } from '../../src/parser/parse.js';
import { toCamelCase } from '../../src/utils/naming.js';
import {
  planOperations,
  generateCamelPayload,
  generateCamelQueryParams,
  delay,
  parseCliArgs,
  IdRegistry,
  getExpectedStatusCodes,
  isUnexpectedStatus,
  type CapturedExchange,
  type ExchangeProvenance,
  type SmokeResults,
} from './shared.js';

const DELAY_MS = Number(process.env.SMOKE_DELAY_MS ?? '200');

// ---------------------------------------------------------------------------
// SDK method resolution
// ---------------------------------------------------------------------------

/** Get all method names from a resource's prototype chain */
function getResourceMethods(resource: object): string[] {
  const methods: string[] = [];
  let proto = Object.getPrototypeOf(resource);
  while (proto && proto !== Object.prototype) {
    for (const name of Object.getOwnPropertyNames(proto)) {
      if (name !== 'constructor' && typeof (proto as Record<string, unknown>)[name] === 'function') {
        methods.push(name);
      }
    }
    proto = Object.getPrototypeOf(proto);
  }
  return Array.from(new Set(methods));
}

/** Split a camelCase/PascalCase name into lowercase words */
function splitToWords(name: string): string[] {
  return name
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
    .split(/[\s_]+/)
    .filter(Boolean)
    .map((w) => w.toLowerCase());
}

/** Standard CRUD verb → SDK method prefixes */
const VERB_PREFIX_MAP: Record<string, string[]> = {
  create: ['create'],
  list: ['list'],
  get: ['get'],
  retrieve: ['get'],
  update: ['update'],
  delete: ['delete'],
};

/** Synonym map for keyword matching (IR term → SDK term) */
const VERB_SYNONYMS: Record<string, string> = {
  retrieve: 'get',
  delete: 'remove',
};

/** Naive singularize for comparison: directories→directory, keys→key, etc. */
function stem(word: string): string {
  if (word.endsWith('ies') && word.length > 4) return word.slice(0, -3) + 'y';
  if (word.endsWith('ses') && word.length > 4) return word.slice(0, -2);
  if (word.length > 3 && word.endsWith('s')) return word.slice(0, -1);
  return word;
}

interface MethodResolution {
  name: string;
  fn: Function;
  tier: 'exact' | 'crud-prefix' | 'fuzzy' | 'manifest';
  confidence: number;
}

// ---------------------------------------------------------------------------
// Smoke manifest (generated by codegen, used for deterministic method resolution)
// ---------------------------------------------------------------------------

interface ManifestEntry {
  operationId: string;
  sdkResourceProperty: string;
  sdkMethodName: string;
  httpMethod: string;
  path: string;
  pathParams: string[];
  bodyFields: string[];
  queryFields: string[];
}

let manifestMap: Map<string, ManifestEntry> | null = null;

function loadManifest(sdkPath: string): void {
  const manifestPath = resolve(sdkPath, 'smoke-manifest.json');
  if (!existsSync(manifestPath)) return;
  try {
    const data = JSON.parse(readFileSync(manifestPath, 'utf-8'));
    manifestMap = new Map<string, ManifestEntry>();
    for (const entry of data.entries as ManifestEntry[]) {
      manifestMap.set(entry.operationId, entry);
    }
    console.log(`Loaded smoke manifest with ${manifestMap.size} entries`);
  } catch {
    console.warn('Failed to load smoke manifest, falling back to fuzzy matching');
  }
}

function resolveFromManifest(
  operationId: string,
  resource: object,
): MethodResolution | undefined {
  if (!manifestMap) return undefined;
  const entry = manifestMap.get(operationId);
  if (!entry) return undefined;
  const res = resource as Record<string, unknown>;
  const fn = res[entry.sdkMethodName];
  if (typeof fn !== 'function') return undefined;
  return { name: entry.sdkMethodName, fn: fn as Function, tier: 'manifest', confidence: 1.0 };
}

/**
 * Resolve an IR operation name to an SDK method by enumerating available
 * methods and fuzzy-matching.  Tries, in order:
 *   1. Exact match
 *   2. Standard CRUD prefix match (prefer candidates containing the service name)
 *   3. Keyword overlap match (with plural normalization; best score above threshold wins)
 *
 * @param serviceName - The IR service name (e.g. "Connections"), used as a
 *   tiebreaker when multiple SDK methods share the same verb prefix.
 */
function resolveSDKMethod(
  opName: string,
  resource: object,
  serviceName: string,
): MethodResolution | undefined {
  const methods = getResourceMethods(resource);
  const res = resource as Record<string, unknown>;

  // 1. Exact match
  if (methods.includes(opName) && typeof res[opName] === 'function') {
    return { name: opName, fn: res[opName] as Function, tier: 'exact', confidence: 1.0 };
  }

  // Lowercase service name words for matching (e.g. "Connections" → ["connection"])
  const serviceWords = splitToWords(serviceName).map(stem);

  // 2. Standard CRUD: match by verb prefix, prefer candidates whose name
  //    contains the service entity (e.g. "listConnections" for service "Connections")
  const prefixes = VERB_PREFIX_MAP[opName];
  if (prefixes) {
    const candidates = methods.filter((m) => prefixes.some((p) => m.startsWith(p)));
    if (candidates.length > 0) {
      // Score by how many service words appear in the method name
      candidates.sort((a, b) => {
        const aWords = splitToWords(a).map(stem);
        const bWords = splitToWords(b).map(stem);
        const aServiceScore = serviceWords.filter((sw) => aWords.includes(sw)).length;
        const bServiceScore = serviceWords.filter((sw) => bWords.includes(sw)).length;
        if (bServiceScore !== aServiceScore) return bServiceScore - aServiceScore;
        // Tie-break by shortest name (primary operation)
        return a.length - b.length;
      });
      return { name: candidates[0], fn: res[candidates[0]] as Function, tier: 'crud-prefix', confidence: 0.8 };
    }
  }

  // 3. Keyword-based fuzzy match for controller-style names
  const opWords = splitToWords(opName).map((w) => VERB_SYNONYMS[w] ?? w);
  const noise = new Set(['controller', 'controllers', 'userland', 'standalone']);
  const opKeywords = opWords.filter((w) => !noise.has(w)).map(stem);

  let bestMatch: string | undefined;
  let bestScore = 0;

  for (const method of methods) {
    const methodStems = splitToWords(method).map(stem);
    const overlap = opKeywords.filter((w) => methodStems.includes(w)).length;
    const score = overlap / Math.max(opKeywords.length, methodStems.length);
    if (score > bestScore) {
      bestScore = score;
      bestMatch = method;
    }
  }

  if (bestMatch && bestScore >= 0.3) {
    return { name: bestMatch, fn: res[bestMatch] as Function, tier: 'fuzzy', confidence: bestScore };
  }

  return undefined;
}

/** Map IR service names to WorkOS SDK property names */
const SERVICE_MAP: Record<string, string> = {
  Organizations: 'organizations',
  OrganizationDomains: 'organizationDomains',
  Users: 'userManagement',
  Connections: 'sso',
  Directories: 'directorySync',
  DirectoryGroups: 'directorySync',
  DirectoryUsers: 'directorySync',
  Events: 'events',
  AuditLogs: 'auditLogs',
  AuditLogExports: 'auditLogs',
  FeatureFlags: 'featureFlags',
  Webhooks: 'webhooks',
  Vault: 'vault',
  ApiKeys: 'apiKeys',
  Portal: 'portal',
  Roles: 'userManagement',
  Permissions: 'userManagement',
  Invitations: 'userManagement',
  Sessions: 'userManagement',
  Memberships: 'userManagement',
  OrganizationMemberships: 'userManagement',
  SSO: 'sso',
  FGA: 'fga',
};

// ---------------------------------------------------------------------------
// Fetch interception
// ---------------------------------------------------------------------------

let capturedExchanges: Array<Partial<CapturedExchange> & { _operationId?: string }> = [];
let currentOperationId: string | null = null;
const originalFetch = globalThis.fetch;

globalThis.fetch = async (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
  const url = new URL(typeof input === 'string' ? input : input instanceof URL ? input.toString() : input.url);

  // Capture the request as-sent (already serialized by SDK)
  const capture: Partial<CapturedExchange> & { _operationId?: string } = {
    request: {
      method: (init?.method ?? 'GET').toUpperCase(),
      path: url.pathname,
      queryParams: Object.fromEntries(Array.from(url.searchParams.entries()).sort()),
      body: init?.body ? safeParseJson(init.body as string) : null,
    },
    _operationId: currentOperationId ?? undefined,
  };
  capturedExchanges.push(capture);

  // Make the real call
  const response = await originalFetch(input, init);
  const cloned = response.clone();
  const responseBody = await cloned.json().catch(() => null);

  capture.response = { status: response.status, body: responseBody };
  return response;
};

/** Return the primary capture for a given operationId, falling back to any with a response */
function getPrimaryCapture(opId: string): Partial<CapturedExchange> | null {
  if (capturedExchanges.length === 0) return null;
  // Prefer captures tagged with this operationId
  const tagged = capturedExchanges.filter((c) => c._operationId === opId && c.response != null);
  if (tagged.length > 0) return tagged[0];
  // Fallback: first with a response, or last entry
  return capturedExchanges.find((c) => c.response != null) ?? capturedExchanges[capturedExchanges.length - 1];
}

function safeParseJson(body: string): unknown {
  try {
    return JSON.parse(body);
  } catch {
    return body;
  }
}

async function main() {
  const { spec: specPath, sdkPath } = parseCliArgs();
  if (!sdkPath) {
    console.error('--sdk-path is required (path to workos-node SDK root, e.g. ../backend/workos-node)');
    process.exit(1);
  }
  const apiKey = process.env.WORKOS_API_KEY;
  if (!apiKey) {
    console.error('WORKOS_API_KEY environment variable is required');
    process.exit(1);
  }

  console.log('Parsing spec...');
  const spec = await parseSpec(specPath);
  console.log(`Spec: ${spec.name} v${spec.version}`);

  // Load smoke manifest if available
  loadManifest(sdkPath);

  // Resolve SDK entry point and load WorkOS after fetch interception is set up.
  // The SDK's .js files are CommonJS but its package.json has "type": "module",
  // so we use createRequire rooted at the SDK entry point, so the SDK's own
  // node_modules are used for all transitive requires.
  const { createRequire } = await import('node:module');
  // Load from lib/index.js which exports WorkOSNode (the Node-specific
  // subclass) as `WorkOS`.
  const sdkIndex = resolve(sdkPath, 'lib/index.js');
  const sdkRequire = createRequire(sdkIndex);
  const { WorkOS } = sdkRequire(sdkIndex);

  // Support WORKOS_BASE_URL for staging/local environments
  const baseUrl = process.env.WORKOS_BASE_URL;
  const workosOptions: Record<string, unknown> = {};
  if (baseUrl) {
    const parsed = new URL(baseUrl);
    workosOptions.apiHostname = parsed.host;
    workosOptions.https = parsed.protocol === 'https:';
    console.log(`Base URL override: ${baseUrl}`);
  }
  const workos = new WorkOS(apiKey, workosOptions);

  const groups = planOperations(spec);
  const ids = new IdRegistry();
  const exchanges: CapturedExchange[] = [];
  const cleanupCallbacks: Array<() => Promise<boolean>> = [];

  console.log(
    `\nPlanned ${groups.reduce((n, g) => n + g.operations.length, 0)} operations across ${groups.length} services\n`,
  );

  for (const group of groups) {
    const sdkProp = SERVICE_MAP[group.service];
    if (!sdkProp) {
      console.log(`\n--- ${group.service} (no SDK mapping, skipping) ---`);
      for (const planned of group.operations) {
        exchanges.push({
          operationId: `${group.service}.${planned.operation.name}`,
          service: group.service,
          operationName: planned.operation.name,
          request: {
            method: planned.operation.httpMethod.toUpperCase(),
            path: planned.operation.path,
            queryParams: {},
            body: null,
          },
          response: { status: 0, body: null },
          outcome: 'skipped',
          error: `No SDK mapping for service "${group.service}"`,
          durationMs: 0,
        });
      }
      continue;
    }

    const resource = (workos as unknown as Record<string, unknown>)[sdkProp];
    if (!resource || typeof resource !== 'object') {
      console.log(`\n--- ${group.service} (SDK property "${sdkProp}" not found, skipping) ---`);
      continue;
    }

    console.log(`\n--- ${group.service} → workos.${sdkProp} ---`);

    for (const planned of group.operations) {
      const op = planned.operation;
      const operationId = `${group.service}.${op.name}`;
      const resolved = resolveFromManifest(operationId, resource as object)
        ?? resolveSDKMethod(toCamelCase(op.name), resource as object, group.service);

      if (!resolved) {
        console.log(`  SKIP ${op.name} (no SDK method matching "${toCamelCase(op.name)}")`);
        exchanges.push({
          operationId,
          service: group.service,
          operationName: op.name,
          request: { method: op.httpMethod.toUpperCase(), path: op.path, queryParams: {}, body: null },
          response: { status: 0, body: null },
          outcome: 'skipped',
          error: `No SDK method matching "${toCamelCase(op.name)}" on ${sdkProp}`,
          durationMs: 0,
        });
        continue;
      }

      const { name: methodName, fn: method } = resolved;

      // Resolve path params
      let resolvedPathParams: Record<string, string> = {};
      if (op.pathParams.length > 0) {
        const resolved = ids.resolvePathParams(op, group.service);
        if (!resolved) {
          console.log(`  SKIP ${op.name} (missing path params)`);
          exchanges.push({
            operationId,
            service: group.service,
            operationName: op.name,
            request: { method: op.httpMethod.toUpperCase(), path: op.path, queryParams: {}, body: null },
            response: { status: 0, body: null },
            outcome: 'skipped',
            error: 'Missing path parameters',
            durationMs: 0,
          });
          continue;
        }
        resolvedPathParams = resolved;
      }

      // Build arguments based on operation shape.
      // Simple single-param operations without body/query → positional: method(id)
      // Everything else with path params → options object merging path params + body/query
      const args: unknown[] = [];

      const isSimplePositionalOp =
        op.pathParams.length === 1 &&
        !op.paginated &&
        !op.requestBody &&
        op.queryParams.filter((q) => q.required).length === 0;

      if (op.pathParams.length === 0) {
        // No path params: body or query params as options object
        if (op.requestBody) {
          const payload = generateCamelPayload(op, spec);
          if (payload) args.push(payload);
        } else if (op.queryParams.length > 0) {
          const queryOpts = generateCamelQueryParams(op, spec);
          if (Object.keys(queryOpts).length > 0) {
            args.push(queryOpts);
          }
        }
        if (op.idempotent && op.httpMethod === 'post') {
          args.push({});
        }
      } else if (isSimplePositionalOp) {
        // Simple positional: method(id)
        args.push(resolvedPathParams[op.pathParams[0].name]);
      } else {
        // Complex: merge path params + body/query into a single options object
        const options: Record<string, unknown> = {};
        for (const p of op.pathParams) {
          options[toCamelCase(p.name)] = resolvedPathParams[p.name];
        }
        if (op.requestBody) {
          const payload = generateCamelPayload(op, spec);
          if (payload) Object.assign(options, payload);
        }
        if (op.queryParams.length > 0) {
          const queryOpts = generateCamelQueryParams(op, spec);
          Object.assign(options, queryOpts);
        }
        args.push(options);
        if (op.idempotent && op.httpMethod === 'post') {
          args.push({});
        }
      }

      capturedExchanges = [];
      currentOperationId = operationId;
      const start = Date.now();

      try {
        const result = await (method as Function).call(resource, ...args);
        const durationMs = Date.now() - start;
        currentOperationId = null;
        const captured = getPrimaryCapture(operationId);

        // Build provenance
        const captureIndex = captured ? capturedExchanges.indexOf(captured as typeof capturedExchanges[number]) : -1;
        const provenance: ExchangeProvenance = {
          resolutionTier: resolved.tier,
          resolutionConfidence: resolved.confidence,
          sdkMethodName: methodName,
          captureIndex: captureIndex >= 0 ? captureIndex : 0,
          totalCaptures: capturedExchanges.length,
        };

        // Build exchange from intercepted fetch data
        const actualStatus = captured?.response?.status ?? 200;
        const unexpected = isUnexpectedStatus(actualStatus, op);
        const exchange: CapturedExchange = {
          operationId,
          service: group.service,
          operationName: op.name,
          request: captured?.request ?? {
            method: op.httpMethod.toUpperCase(),
            path: op.path,
            queryParams: {},
            body: null,
          },
          response: captured?.response ?? { status: 200, body: result },
          outcome: 'success',
          durationMs,
          provenance,
        };
        if (unexpected) {
          exchange.unexpectedStatus = true;
          exchange.expectedStatusCodes = getExpectedStatusCodes(op);
        }

        exchanges.push(exchange);

        // Extract IDs for chaining (only top-level ops store service ID)
        if (captured?.response?.body) {
          ids.extractAndStore(group.service, captured.response.body, op.pathParams.length === 0);
        }

        // Track POST creations for cleanup
        if (op.httpMethod === 'post' && result && typeof result === 'object' && 'id' in result) {
          const deleteResolved = resolveSDKMethod('delete', resource as object, group.service);
          if (deleteResolved) {
            const deleteMethod = deleteResolved.fn;
            const entityId = (result as Record<string, unknown>).id as string;
            cleanupCallbacks.push(async (): Promise<boolean> => {
              try {
                await (deleteMethod as Function).call(resource, entityId);
                console.log(`  Cleaned up: ${group.service} ${entityId}`);
                return true;
              } catch {
                console.log(`  Failed to cleanup: ${group.service} ${entityId}`);
                return false;
              }
            });
          }
        }

        const resolvedTag = methodName !== toCamelCase(op.name) ? ` → ${methodName}` : '';
        const tierTag = resolved.tier !== 'exact' ? ` [${resolved.tier}:${resolved.confidence.toFixed(2)}]` : '';
        console.log(`  OK ${op.name}${resolvedTag}${tierTag} (${durationMs}ms)`);
      } catch (err) {
        const durationMs = Date.now() - start;
        currentOperationId = null;
        const captured = getPrimaryCapture(operationId);
        const errorMsg = err instanceof Error ? err.message : String(err);

        // Build provenance
        const captureIndex = captured ? capturedExchanges.indexOf(captured as typeof capturedExchanges[number]) : -1;
        const provenance: ExchangeProvenance = {
          resolutionTier: resolved.tier,
          resolutionConfidence: resolved.confidence,
          sdkMethodName: methodName,
          captureIndex: captureIndex >= 0 ? captureIndex : 0,
          totalCaptures: capturedExchanges.length,
        };

        // Still capture the exchange — the intercepted fetch data shows what was sent
        const actualStatus = captured?.response?.status ?? 0;
        const unexpected = isUnexpectedStatus(actualStatus, op);
        const exchange: CapturedExchange = {
          operationId,
          service: group.service,
          operationName: op.name,
          request: captured?.request ?? {
            method: op.httpMethod.toUpperCase(),
            path: op.path,
            queryParams: {},
            body: null,
          },
          response: captured?.response ?? { status: 0, body: null },
          outcome: 'api-error',
          error: errorMsg,
          durationMs,
          provenance,
        };
        if (unexpected) {
          exchange.unexpectedStatus = true;
          exchange.expectedStatusCodes = getExpectedStatusCodes(op);
        }

        // If we got a response from the interceptor, extract IDs even on error
        if (captured?.response?.body && captured.response.status < 400) {
          ids.extractAndStore(group.service, captured.response.body, op.pathParams.length === 0);
        }

        exchanges.push(exchange);
        const unexpectedTag = unexpected ? ' UNEXPECTED' : '';
        const errResolvedTag = methodName !== toCamelCase(op.name) ? ` → ${methodName}` : '';
        const tierTag = resolved.tier !== 'exact' ? ` [${resolved.tier}:${resolved.confidence.toFixed(2)}]` : '';
        console.log(`  ERR ${op.name}${errResolvedTag}${tierTag}: ${errorMsg} (${durationMs}ms)${unexpectedTag}`);
      }

      await delay(DELAY_MS);
    }
  }

  // Cleanup
  console.log('\n--- Cleanup ---');
  let cleanupFailures = 0;
  for (const cleanup of cleanupCallbacks.reverse()) {
    const ok = await cleanup();
    if (!ok) cleanupFailures++;
    await delay(DELAY_MS);
  }

  // Restore original fetch
  globalThis.fetch = originalFetch;

  // Write results
  const results: SmokeResults = {
    source: 'sdk-node',
    timestamp: new Date().toISOString(),
    specVersion: spec.version,
    exchanges,
  };

  writeFileSync('smoke-results-sdk-node.json', JSON.stringify(results, null, 2));

  const successes = exchanges.filter((e) => e.outcome === 'success').length;
  const errors = exchanges.filter((e) => e.outcome === 'api-error').length;
  const skipped = exchanges.filter((e) => e.outcome === 'skipped').length;
  const unexpectedCount = exchanges.filter((e) => e.unexpectedStatus).length;

  console.log(
    `\nResults: ${successes} success, ${errors} api-error, ${skipped} skipped, ${unexpectedCount} unexpected status, ${cleanupFailures} cleanup failures`,
  );
  if (unexpectedCount > 0) {
    console.log('\nUnexpected status codes:');
    for (const e of exchanges.filter((e) => e.unexpectedStatus)) {
      console.log(`  ${e.operationId}: got ${e.response.status}, expected ${e.expectedStatusCodes?.join('/')}`);
    }
  }
  console.log('Written to smoke-results-sdk-node.json');
}

main().catch((err) => {
  console.error('Smoke test crashed:', err);
  globalThis.fetch = originalFetch;
  process.exit(1);
});
