// This file is auto-generated by oagen. Do not edit.

import Foundation

/// The spec-driven resource accessors for ``WorkOSClient``. The client class
/// itself is hand-maintained in `WorkOSClient.swift`.
extension WorkOSClient {
    /// Operations for the Organizations API.
    public var organizations: Organizations { Organizations(transport: transport) }

    /// Operations for the Sso API.
    public var sso: Sso { Sso(transport: transport) }
}
