import { toCamelCase } from '../../utils/naming.js';

export function oagenScripts(lang: string): Record<string, string> {
  return {
    [`sdk:generate:${lang}`]: `oagen generate --lang ${lang} --output ./sdk --namespace workos --spec open-api-spec.yaml --api-surface ./sdk-${lang}-surface.json --target ../your-${lang}-sdk`,
    [`sdk:diff:${lang}`]: `oagen diff --old ./sdk/spec-snapshot.yaml --new open-api-spec.yaml --lang ${lang} --output ./sdk --target ../your-${lang}-sdk --api-surface ./sdk-${lang}-surface.json`,
    [`sdk:verify:${lang}`]: `oagen verify --lang ${lang} --output ./sdk --spec open-api-spec.yaml --api-surface ./sdk-${lang}-surface.json`,
    [`sdk:extract:${lang}`]: `oagen extract --lang ${lang} --sdk-path ../your-${lang}-sdk --output ./sdk-${lang}-surface.json`,
  };
}

export function packageJson(lang: string): string {
  return JSON.stringify(
    {
      name: `custom-oagen-emitters`,
      version: '0.0.1',
      type: 'module',
      main: 'dist/index.js',
      types: 'dist/index.d.ts',
      exports: {
        '.': { types: './dist/index.d.ts', import: './dist/index.js' },
      },
      scripts: {
        build: 'tsup',
        test: 'vitest run',
        'test:watch': 'vitest',
        typecheck: 'tsc --noEmit',
        ...oagenScripts(lang),
      },
      dependencies: {
        '@workos/oagen': '^0.0.1',
      },
      devDependencies: {
        tsup: '^8.4.0',
        tsx: '^4.19.0',
        vitest: '^3.0.0',
        '@types/node': '^25.3.3',
      },
    },
    null,
    2,
  );
}

export function tsconfigJson(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'bundler',
        strict: true,
        declaration: true,
        declarationMap: true,
        sourceMap: true,
        outDir: 'dist',
        rootDir: '.',
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
        resolveJsonModule: true,
        isolatedModules: true,
      },
      include: ['src', 'test'],
      exclude: ['node_modules', 'dist'],
    },
    null,
    2,
  );
}

export function vitestConfig(): string {
  return `import { defineConfig } from 'vitest/config';
export default defineConfig({
  test: { globals: true, include: ['test/**/*.test.ts'] },
});
`;
}

export function tsupConfig(): string {
  return `import { defineConfig } from 'tsup';
export default defineConfig({
  entry: { index: 'src/index.ts' },
  format: ['esm'],
  dts: true,
  clean: true,
  target: 'node20',
});
`;
}

export function oagenConfig(lang: string): string {
  const varName = `${toCamelCase(lang)}Emitter`;
  return `import type { OagenConfig } from '@workos/oagen';
import { ${varName} } from './src/${lang}/index.js';

const config: OagenConfig = {
  emitters: [${varName}],
};
export default config;
`;
}

export function srcIndex(lang: string): string {
  const varName = `${toCamelCase(lang)}Emitter`;
  return `export { ${varName} } from './${lang}/index.js';
`;
}

export function gitignore(): string {
  return `node_modules/
dist/
.env
sdk-*-surface.json
smoke-*.json
sdk/
`;
}

export function stubEmitter(lang: string): string {
  const varName = `${toCamelCase(lang)}Emitter`;
  return `import type { Emitter, EmitterContext, GeneratedFile, ApiSpec, Model, Enum, Service } from '@workos/oagen';
import { IR_VERSION } from '@workos/oagen';

export const ${varName}: Emitter = {
  language: '${lang}',
  contractVersion: IR_VERSION,

  generateModels(_models: Model[], _ctx: EmitterContext): GeneratedFile[] {
    return [];
  },

  generateEnums(_enums: Enum[], _ctx: EmitterContext): GeneratedFile[] {
    return [];
  },

  generateResources(_services: Service[], _ctx: EmitterContext): GeneratedFile[] {
    return [];
  },

  generateClient(_spec: ApiSpec, _ctx: EmitterContext): GeneratedFile[] {
    return [];
  },

  generateErrors(_ctx: EmitterContext): GeneratedFile[] {
    return [];
  },

  generateConfig(_ctx: EmitterContext): GeneratedFile[] {
    return [];
  },

  generateTypeSignatures(_spec: ApiSpec, _ctx: EmitterContext): GeneratedFile[] {
    return [];
  },

  generateTests(_spec: ApiSpec, _ctx: EmitterContext): GeneratedFile[] {
    return [];
  },

  generateManifest(_spec: ApiSpec, _ctx: EmitterContext): GeneratedFile[] {
    return [];
  },

  fileHeader(): string {
    return '// Auto-generated by oagen. Do not edit.';
  },
};
`;
}
