import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import type { GeneratedFile } from './types.js';
import { mergeIntoExisting, hasGrammar, extractClassEndLines } from './merger.js';
import { deepMergeJson } from './json-merge.js';
import { getMergeAdapter } from './merge-adapters/index.js';

export interface WriteOptions {
  /** The emitter language (e.g., "node", "ruby"). Used to select the
   *  tree-sitter grammar for AST-level merging. */
  language?: string;
  /** The auto-generated file header string. */
  header?: string;
}

export interface WriteResult {
  written: string[];
  merged: string[];
  skipped: string[];
  identical: string[];
  ignored: string[];
}

/**
 * Write generated files to disk with AST-level merging.
 *
 * When a file already exists:
 * - skipIfExists → leave it alone entirely
 * - AST merge available → parse both, append only new symbols
 * - No grammar → skip (never clobber hand-written code)
 *
 * New files are always written in full.
 */
export async function writeFiles(
  files: GeneratedFile[],
  outputDir: string,
  options?: WriteOptions,
): Promise<WriteResult> {
  const result: WriteResult = { written: [], merged: [], skipped: [], identical: [], ignored: [] };
  const sorted = [...files].sort((a, b) => a.path.localeCompare(b.path));
  const language = options?.language;
  const header = options?.header ?? '';

  for (const file of sorted) {
    const fullPath = path.join(outputDir, file.path);

    // Check if file already exists
    let existingContent: string | null = null;
    try {
      existingContent = await fs.readFile(fullPath, 'utf-8');
    } catch {
      // File doesn't exist
    }

    // New file → write in full
    if (existingContent === null) {
      await fs.mkdir(path.dirname(fullPath), { recursive: true });
      await fs.writeFile(fullPath, file.content, 'utf-8');
      result.written.push(file.path);
      continue;
    }

    // skipIfExists → hard skip, no merge (but ensure header is present)
    if (file.skipIfExists) {
      if (header && !existingContent.startsWith(header)) {
        await fs.writeFile(fullPath, header + '\n\n' + existingContent, 'utf-8');
      }
      result.skipped.push(file.path);
      continue;
    }

    // @oagen-ignore-file → skip entirely (existing file opts out of all generation)
    if (existingContent.includes('@oagen-ignore-file')) {
      result.ignored.push(file.path);
      continue;
    }

    // Don't merge test files into hand-written test files — generated tests are
    // designed for the standalone generated SDK and will have wrong
    // signatures/fixtures when merged into hand-written tests.
    // However, if the existing test file is itself auto-generated (has the oagen
    // header), allow overwriteExisting to take effect so new methods get coverage.
    const adapter = language ? getMergeAdapter(language) : undefined;
    const isTestFile = adapter?.testFilePatterns
      ? adapter.testFilePatterns.some((p) => p.test(file.path))
      : isDefaultTestFile(file.path);
    if (isTestFile) {
      const isExistingAutoGenerated = header && existingContent.startsWith(header);
      if (!isExistingAutoGenerated) {
        result.skipped.push(file.path);
        continue;
      }
      // Auto-generated test file — fall through to overwriteExisting / identical checks
    }

    // Identical content → no-op
    if (existingContent === file.content) {
      result.identical.push(file.path);
      continue;
    }

    // Force overwrite — but preserve any @oagen-ignore regions from existing content
    if (file.overwriteExisting) {
      const content =
        existingContent.includes('@oagen-ignore-start') && language && hasGrammar(language)
          ? await overwriteWithPreservedRegions(existingContent, file.content, language)
          : file.content;
      await fs.writeFile(fullPath, content, 'utf-8');
      result.written.push(file.path);
      continue;
    }

    // JSON files → deep merge preserving existing keys
    if (file.path.endsWith('.json')) {
      try {
        const existingJson = JSON.parse(existingContent);
        const generatedJson = JSON.parse(file.content);
        const merged = deepMergeJson(existingJson, generatedJson);
        const mergedContent = JSON.stringify(merged, null, 2) + '\n';
        if (mergedContent === existingContent) {
          result.identical.push(file.path);
        } else {
          await fs.writeFile(fullPath, mergedContent, 'utf-8');
          result.merged.push(file.path);
        }
      } catch {
        // Parse failed — fall back to overwrite
        await fs.writeFile(fullPath, file.content, 'utf-8');
        result.written.push(file.path);
      }
      continue;
    }

    // Source files with grammar → AST-level merge
    if (language && hasGrammar(language)) {
      try {
        const mergeResult = await mergeIntoExisting(existingContent, file.content, language, header);

        // Ensure header is present on merged content
        let finalContent = mergeResult.content;
        if (header && !finalContent.startsWith(header)) {
          finalContent = header + '\n\n' + finalContent;
        }

        if (!mergeResult.changed && finalContent === existingContent) {
          result.identical.push(file.path);
          continue;
        }

        await fs.writeFile(fullPath, finalContent, 'utf-8');
        result.merged.push(file.path);
        continue;
      } catch (err) {
        // AST merge failed (e.g. tree-sitter grammar ABI issue) — fall back to overwrite
        console.warn(
          `[oagen] AST merge failed for ${file.path}, falling back to overwrite.${err instanceof Error ? ` ${err.message}` : ''}`,
        );
        await fs.writeFile(fullPath, file.content, 'utf-8');
        result.written.push(file.path);
        continue;
      }
    }

    // No grammar available → skip to avoid clobbering
    result.skipped.push(file.path);
  }

  return result;
}

/** Comprehensive fallback when no adapter is available. */
function isDefaultTestFile(filePath: string): boolean {
  return (
    /\.(spec|test)\.[jt]sx?$/.test(filePath) ||
    filePath.endsWith('_test.go') ||
    filePath.endsWith('_test.rb') ||
    filePath.endsWith('_spec.rb') ||
    /(?:^|\/)test_.*\.py$/.test(filePath) ||
    filePath.endsWith('_test.py') ||
    filePath.endsWith('Test.php') ||
    filePath.endsWith('_test.rs') ||
    /(?:^|\/)tests\/.*\.rs$/.test(filePath)
  );
}

// --- @oagen-ignore region preservation for overwriteExisting ---

/**
 * Overwrite a file with generated content while preserving
 * `@oagen-ignore-start` / `@oagen-ignore-end` regions (and their
 * required imports) from the existing file.
 *
 * Uses tree-sitter via `extractClassEndLines` to find accurate class
 * boundaries so ignore blocks are inserted at the correct position even
 * when docstrings contain unindented text.
 */
export async function overwriteWithPreservedRegions(
  existingContent: string,
  generatedContent: string,
  language: string,
): Promise<string> {
  const existingLines = existingContent.split('\n');
  const generatedLines = generatedContent.split('\n');

  // 1. Extract ignore blocks and their containing class from existing content.
  const blocks: { containingClass: string; lines: string[] }[] = [];
  for (let i = 0; i < existingLines.length; i++) {
    if (!existingLines[i].includes('@oagen-ignore-start')) continue;
    const startIdx = i;
    while (i < existingLines.length && !existingLines[i].includes('@oagen-ignore-end')) i++;
    blocks.push({
      containingClass: findContainingClass(existingLines, startIdx),
      lines: existingLines.slice(startIdx, i + 1),
    });
  }
  if (blocks.length === 0) return generatedContent;

  // 2. Splice extra imports from existing into generated
  const result = [...generatedLines];
  spliceExtraImports(existingLines, result);

  // 3. Build class-end map from the generated content (after import splicing)
  //    via tree-sitter for accurate boundary detection.
  const genSource = result.join('\n');
  const classEndLines = await extractClassEndLines(genSource, language);

  // 4. Group ignore blocks by class and determine insertion points
  const blocksByClass = new Map<string, string[][]>();
  for (const b of blocks) {
    if (!blocksByClass.has(b.containingClass)) blocksByClass.set(b.containingClass, []);
    blocksByClass.get(b.containingClass)!.push(b.lines);
  }

  // 4a. Handle replacement blocks: ignore blocks that redefine their
  //     containing class replace the generated class entirely.
  //     Also handles top-level blocks (no containing class) that define
  //     a class matching one in the generated content.
  const replacedClasses = new Set<string>();
  const handledBlockKeys = new Set<string>();
  const replacements: { startLine: number; endLine: number; content: string[] }[] = [];
  for (const [className, classBlocks] of blocksByClass) {
    // Determine the target class for replacement.  When the block has a
    // containing class, we check if the block redefines that class.  When
    // there is no containing class (top-level ignore block), we look for a
    // class definition inside the block that matches a generated class.
    let targetClass = className;
    if (!targetClass) {
      for (const blockLines of classBlocks) {
        for (const l of blockLines) {
          const m = l.match(/^(?:export\s+)?class\s+(\w+)/);
          if (m && classEndLines.has(m[1])) {
            targetClass = m[1];
            break;
          }
        }
        if (targetClass) break;
      }
    }
    if (!targetClass) continue;
    const isReplacement = classBlocks.some((blockLines) =>
      blockLines.some((l) => {
        const m = l.match(/^(?:export\s+)?class\s+(\w+)/);
        return m?.[1] === targetClass;
      }),
    );
    if (!isReplacement) continue;
    const info = classEndLines.get(targetClass);
    if (!info) continue;
    const startLine = findClassDeclarationStart(result, targetClass, info.bodyEndLine);
    if (startLine < 0) continue;
    const content: string[] = [];
    for (const block of classBlocks) {
      content.push('');
      content.push(...block);
    }
    replacements.push({ startLine, endLine: info.bodyEndLine, content });
    replacedClasses.add(targetClass);
    handledBlockKeys.add(className);
  }
  // Apply replacements bottom-up to preserve line indices
  replacements.sort((a, b) => b.startLine - a.startLine);
  for (const rep of replacements) {
    result.splice(rep.startLine, rep.endLine - rep.startLine, ...rep.content);
  }

  // 4b. Standard insertions for non-replacement blocks
  // Rebuild class end lines if replacements shifted line numbers.
  let effectiveClassEndLines = classEndLines;
  if (replacedClasses.size > 0) {
    effectiveClassEndLines = await extractClassEndLines(result.join('\n'), language);
  }

  const insertions: { line: number; content: string[] }[] = [];
  for (const [className, classBlocks] of blocksByClass) {
    if (handledBlockKeys.has(className) || replacedClasses.has(className)) continue;
    const info = className ? effectiveClassEndLines.get(className) : undefined;
    const insertLine = info ? info.bodyEndLine : result.length;
    const content: string[] = [];
    for (const block of classBlocks) {
      content.push('');
      content.push(...block);
    }
    insertions.push({ line: insertLine, content });
  }

  // Apply bottom-up to preserve line indices
  insertions.sort((a, b) => b.line - a.line);
  for (const ins of insertions) {
    result.splice(ins.line, 0, ...ins.content);
  }

  return result.join('\n');
}

/** Scan backwards from `lineIdx` to find the nearest class declaration name. */
function findContainingClass(lines: string[], lineIdx: number): string {
  for (let j = lineIdx - 1; j >= 0; j--) {
    const m = lines[j].match(/^(?:export\s+)?class\s+(\w+)/);
    if (m) return m[1];
  }
  return '';
}

/**
 * Find the start line of a class declaration (including decorators above it)
 * by scanning backwards from `beforeLine`.
 */
function findClassDeclarationStart(lines: string[], className: string, beforeLine: number): number {
  const classPattern = new RegExp(`^(?:export\\s+)?class\\s+${className}\\b`);
  for (let i = beforeLine - 1; i >= 0; i--) {
    if (!classPattern.test(lines[i])) continue;
    // Scan backward past decorators
    let start = i;
    while (start > 0 && /^\s*@\w+/.test(lines[start - 1])) {
      start--;
    }
    return start;
  }
  return -1;
}

/**
 * Collect `from X import Y, Z` identifiers grouped by module, handling
 * both single-line and multiline (parenthesized) forms.
 */
function collectFromImports(lines: string[]): Map<string, Set<string>> {
  const byModule = new Map<string, Set<string>>();
  for (let i = 0; i < lines.length; i++) {
    if (!/^from\s+/.test(lines[i])) continue;

    let fullText = lines[i];
    if (fullText.includes('(') && !fullText.includes(')')) {
      while (i + 1 < lines.length) {
        i++;
        fullText += ' ' + lines[i].trim();
        if (lines[i].includes(')')) break;
      }
    }

    const normalized = fullText.replace(/[()]/g, '').replace(/\s+/g, ' ').trim();
    const match = normalized.match(/^from\s+(\S+)\s+import\s+(.+)$/);
    if (!match) continue;

    const mod = match[1];
    if (!byModule.has(mod)) byModule.set(mod, new Set());
    for (const id of match[2]
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean)) {
      byModule.get(mod)!.add(id);
    }
  }
  return byModule;
}

/**
 * Add imports from the existing file that are absent from the generated
 * result. Handles both `import X` and `from X import Y` forms.
 * Mutates `resultLines` in place.
 */
function spliceExtraImports(existingLines: string[], resultLines: string[]): void {
  const isSimpleImport = (l: string) => /^import\s+\w/.test(l);

  // Simple imports (import hashlib, import json, …)
  const existingSimple = new Set(existingLines.filter(isSimpleImport).map((l) => l.trim()));
  const generatedSimple = new Set(resultLines.filter(isSimpleImport).map((l) => l.trim()));
  const extraSimple = [...existingSimple].filter((l) => !generatedSimple.has(l));

  // From-imports — compare by module and find extra identifiers
  const existingFrom = collectFromImports(existingLines);
  const generatedFrom = collectFromImports(resultLines);

  // Build a set of all identifiers imported by the generated file (across all modules)
  // so we can detect when an existing barrel import's identifiers are covered by
  // more-specific generated imports (e.g., `from x.y import Z` covers `from x import Z`).
  const allGeneratedIds = new Set<string>();
  for (const ids of generatedFrom.values()) {
    for (const id of ids) allGeneratedIds.add(id);
  }

  const extraFromLines: string[] = [];
  for (const [mod, existIds] of existingFrom) {
    const genIds = generatedFrom.get(mod);
    if (!genIds) {
      // The exact module isn't in the generated file — but check whether every
      // identifier is already imported from a different (e.g., more-specific) module.
      const extra = [...existIds].filter((id) => !allGeneratedIds.has(id));
      if (extra.length > 0) {
        extraFromLines.push(`from ${mod} import ${extra.join(', ')}`);
      }
    } else {
      const extra = [...existIds].filter((id) => !genIds.has(id) && !allGeneratedIds.has(id));
      if (extra.length > 0) {
        extraFromLines.push(`from ${mod} import ${extra.join(', ')}`);
      }
    }
  }

  const allExtra = [...extraSimple, ...extraFromLines];
  if (allExtra.length === 0) return;

  // Find last import line in resultLines (accounting for multiline imports)
  let lastImportIdx = -1;
  for (let i = 0; i < resultLines.length; i++) {
    if (isSimpleImport(resultLines[i]) || /^from\s+/.test(resultLines[i])) {
      lastImportIdx = i;
      if (resultLines[i].includes('(') && !resultLines[i].includes(')')) {
        while (i + 1 < resultLines.length) {
          i++;
          lastImportIdx = i;
          if (resultLines[i].includes(')')) break;
        }
      }
    }
  }

  if (lastImportIdx >= 0) {
    resultLines.splice(lastImportIdx + 1, 0, ...allExtra);
  }
}
