import { readdirSync, unlinkSync, statSync, openSync, readSync, closeSync } from 'node:fs';
import * as path from 'node:path';
import { buildOverlayLookup, patchOverlay, isPatchableChange } from '../compat/overlay.js';
import { getExtractor } from '../compat/extractor-registry.js';
import type { ApiSurface } from '../compat/types.js';
import type { ApiSpec } from '../ir/types.js';
import { getEmitter } from '../engine/registry.js';
import { generate } from '../engine/orchestrator.js';
import { runCompatCheck } from './run-compat-check.js';
import type { OverlayRetryResult } from './types.js';
import { readManifestSync } from '../engine/manifest-reader.js';

/** Generated file header markers used by various emitters. */
const GENERATED_MARKERS = ['Code generated by oagen', 'auto-generated by oagen', 'This file is auto-generated'];

/**
 * Delete oagen-generated source files so the retry loop can regenerate them
 * with overlay-corrected names. Only deletes files that contain an oagen
 * generation marker, preserving hand-written files.
 */
function cleanGeneratedFiles(dir: string): void {
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return;
  }
  for (const entry of entries) {
    const full = path.join(dir, entry);
    let stat;
    try {
      stat = statSync(full);
    } catch {
      continue;
    }
    if (stat.isDirectory()) {
      cleanGeneratedFiles(full);
      continue;
    }
    // Skip non-source files and manifests
    if (entry.endsWith('.json') || entry.endsWith('.lock')) continue;
    // Read only the first 200 bytes to check for generation marker
    try {
      const buf = Buffer.alloc(200);
      const fd = openSync(full, 'r');
      try {
        readSync(fd, buf, 0, 200, 0);
      } finally {
        closeSync(fd);
      }
      const header = buf.toString('utf-8');
      if (GENERATED_MARKERS.some((m) => header.includes(m))) {
        unlinkSync(full);
      }
    } catch {
      // ignore read/delete errors
    }
  }
}

export async function runOverlayRetryLoop(opts: {
  baseline: ApiSurface;
  parsedSpec: ApiSpec;
  outputDir: string;
  lang: string;
  maxRetries: number;
  namespace?: string;
  onRetry?: (attemptNumber: number, maxRetries: number, patchableCount: number) => void;
}): Promise<OverlayRetryResult> {
  const { baseline, parsedSpec, outputDir, lang, maxRetries, namespace, onRetry } = opts;

  const manifest = readManifestSync(outputDir);
  // Pass language-specific hints so property-to-class matching works correctly
  // (e.g., Ruby snake_case "api_keys" → PascalCase "ApiKeys").
  const extractor = getExtractor(lang);
  let overlay = buildOverlayLookup(baseline, manifest, parsedSpec, extractor.hints);
  let prevPreserved = -1;
  const patchedPerIteration: number[] = [];

  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    const compatResult = await runCompatCheck(baseline, outputDir, lang, parsedSpec);
    if (compatResult.passed) {
      return {
        status: 'passed',
        attempts: attempt,
        patchedPerIteration,
        compatResult,
      };
    }

    if (attempt === maxRetries) {
      return {
        status: 'max-retries',
        attempts: attempt,
        patchedPerIteration,
        compatResult,
      };
    }

    const patchable = compatResult.diff.changes.filter(isPatchableChange);
    if (patchable.length === 0) {
      return {
        status: 'no-patchable',
        attempts: attempt,
        patchedPerIteration,
        compatResult,
      };
    }

    const currentBreaking = compatResult.diff.summary.breaking;
    // Stall detection: if breaking count hasn't decreased, we're not making progress
    if (attempt > 0 && currentBreaking >= prevPreserved) {
      return {
        status: 'stalled',
        attempts: attempt,
        patchedPerIteration,
        compatResult,
      };
    }
    prevPreserved = currentBreaking;
    patchedPerIteration.push(patchable.length);
    onRetry?.(attempt + 1, maxRetries, patchable.length);

    overlay = patchOverlay(overlay, patchable, baseline);

    // Pre-delete generated source files so the writer creates them fresh
    // with overlay-corrected names. Without this, the AST merger would preserve
    // old method/class names from the existing files.
    // Only delete files that look like oagen-generated source files (have the header).
    cleanGeneratedFiles(outputDir);

    const emitter = getEmitter(lang);
    await generate(parsedSpec, emitter, {
      namespace: namespace ?? parsedSpec.name,
      outputDir,
      overlayLookup: overlay,
      apiSurface: baseline,
    });
  }

  const compatResult = await runCompatCheck(baseline, outputDir, lang, parsedSpec);
  return {
    status: 'max-retries',
    attempts: maxRetries,
    patchedPerIteration,
    compatResult,
  };
}
