import type { ApiSpec, Model, Enum, Service } from '../../ir/types.js';
import type { Emitter, EmitterContext, GeneratedFile } from '../../engine/types.js';
import { generateModels } from './models.js';
import { generateEnums } from './enums.js';
import { generateResources } from './resources.js';
import { generateClient } from './client.js';
import { generateErrors } from './errors.js';
import { generateConfig } from './config.js';
import { generateCommon } from './common.js';
import { generateOptions } from './options.js';
import { generateTests } from './tests.js';
import { generateManifest } from './manifest.js';

export const nodeEmitter: Emitter = {
  language: 'node',

  generateModels(models: Model[], ctx: EmitterContext): GeneratedFile[] {
    return generateModels(models, ctx);
  },

  generateEnums(enums: Enum[], ctx: EmitterContext): GeneratedFile[] {
    return generateEnums(enums, ctx);
  },

  generateResources(services: Service[], ctx: EmitterContext): GeneratedFile[] {
    return [...generateResources(services, ctx), ...generateOptions(services, ctx)];
  },

  generateClient(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return generateClient(spec, ctx);
  },

  generateErrors(ctx: EmitterContext): GeneratedFile[] {
    return generateErrors(ctx);
  },

  generateConfig(ctx: EmitterContext): GeneratedFile[] {
    return [...generateConfig(ctx), ...generateCommon(ctx)];
  },

  generateTypeSignatures(_spec: ApiSpec, _ctx: EmitterContext): GeneratedFile[] {
    return []; // TypeScript has inline types, no separate signature files needed
  },

  generateTests(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return generateTests(spec, ctx);
  },

  generateManifest(spec: ApiSpec, ctx: EmitterContext): GeneratedFile[] {
    return generateManifest(spec, ctx);
  },

  fileHeader(): string {
    return '// This file is auto-generated by oagen. Do not edit manually.';
  },
};
