# This file is auto-generated by oagen. Do not edit.
defmodule Acme.GrantType do
  @moduledoc """
  GrantType enum.
  """

  @type t :: :urn_grant | :password

  @doc "All known values."
  @spec values() :: [t()]
  def values, do: [:urn_grant, :password]

  @doc "Casts a wire string to its atom; unknown values pass through unchanged."
  @spec cast(String.t() | nil) :: t() | String.t() | nil
  def cast("urn:ietf:params:oauth:grant-type:token-exchange"), do: :urn_grant
  def cast("password"), do: :password
  def cast(other), do: other

  @doc "Dumps an atom back to its wire string."
  @spec dump(t() | String.t()) :: String.t()
  def dump(:urn_grant), do: "urn:ietf:params:oauth:grant-type:token-exchange"
  def dump(:password), do: "password"
  def dump(other) when is_binary(other), do: other
end
