# This file is auto-generated by oagen. Do not edit.
defmodule Acme.Organizations do
  @moduledoc """
  Operations for the Organizations API.
  """

  @doc """
  Get organization.

  ## Parameters

    * `id` — path parameter
    * `opts` — per-request options (see `Acme.Client.request/5`)
  """
  @spec get_organization(Acme.Client.t(), String.t(), keyword()) ::
          {:ok, term()} | {:error, Acme.Error.error()}
  def get_organization(client, id, opts \\ []) do
    Acme.Client.request(
      client,
      :get,
      "/organizations/#{URI.encode(id, &URI.char_unreserved?/1)}",
      %{},
      opts
    )
  end

  @doc """
  List organizations.
  """
  @spec list_organizations(Acme.Client.t(), map(), keyword()) ::
          {:ok, term()} | {:error, Acme.Error.error()}
  def list_organizations(client, params \\ %{}, opts \\ []) do
    Acme.Client.request(client, :get, "/organizations", params, opts)
  end
end
