# This file is auto-generated by oagen. Do not edit.
defmodule Acme.Priority do
  @moduledoc """
  Priority enum.
  """

  @type t :: 1 | 2

  @doc "All known values."
  @spec values() :: [t()]
  def values, do: [1, 2]

  @doc "Casts a wire value; non-string enums pass values through unchanged."
  @spec cast(term()) :: term()
  def cast(value), do: value

  @doc "Dumps a value back to its wire form."
  @spec dump(term()) :: term()
  def dump(value), do: value
end
