# This file is auto-generated by oagen. Do not edit.
defmodule Acme.Scope do
  @moduledoc """
  Scope enum exercising quoted-atom edge cases: members containing `]`,
  backslash escapes, and legacy dump/1 clauses absent from values/0.
  """

  @type t :: atom()

  @doc "All known values."
  @spec values() :: [t()]
  def values,
    do: [
      :"scope:[read]",
      :"tab\tseparated",
      :plain
    ]

  @doc "Casts a wire string to its atom; unknown values pass through unchanged."
  @spec cast(String.t() | nil) :: t() | String.t() | nil
  def cast("scope:[read]"), do: :"scope:[read]"
  def cast("tab\tseparated"), do: :"tab\tseparated"
  def cast("plain"), do: :plain
  def cast(other), do: other

  @doc "Dumps an atom back to its wire string."
  @spec dump(t() | String.t()) :: String.t()
  def dump(:"scope:[read]"), do: "scope:[read]"
  def dump(:"tab\tseparated"), do: "tab\tseparated"
  def dump(:plain), do: "plain"
  def dump(:legacy_removed), do: "legacy"
  def dump(other) when is_binary(other), do: other
end
