# This file is auto-generated by oagen. Do not edit.
defmodule Acme.VerificationStrategy do
  @moduledoc """
  VerificationStrategy enum.
  """

  @type t :: :dns | :manual

  @doc "All known values."
  @spec values() :: [t()]
  def values,
    do: [
      :dns,
      :manual
    ]

  @doc "Casts a wire string to its atom; unknown values pass through unchanged."
  @spec cast(String.t() | nil) :: t() | String.t() | nil
  def cast("dns"), do: :dns
  def cast("manual"), do: :manual
  def cast(other), do: other

  @doc "Dumps an atom back to its wire string."
  @spec dump(t() | String.t()) :: String.t()
  def dump(:dns), do: "dns"
  def dump(:manual), do: "manual"
  def dump(other) when is_binary(other), do: other
end
