// This file is auto-generated by oagen. Do not edit.

import Foundation

/// An Organization.
public struct Organization: Codable, Sendable, Equatable {
    /// Unique identifier of the Organization.
    public let id: String
    /// The name of the Organization.
    public let name: String
    /// Whether connections within this Organization allow profiles outside of their domains.
    public let allowProfilesOutsideOrganization: Bool?
    /// The domains of the Organization.
    public let domains: [OrganizationDomain]?
    /// Arbitrary key-value metadata.
    public let metadata: [String: AnyCodable]?

    public init(
        id: String,
        name: String,
        allowProfilesOutsideOrganization: Bool? = nil,
        domains: [OrganizationDomain]? = nil,
        metadata: [String: AnyCodable]? = nil
    ) {
        self.id = id
        self.name = name
        self.allowProfilesOutsideOrganization = allowProfilesOutsideOrganization
        self.domains = domains
        self.metadata = metadata
    }

    private enum CodingKeys: String, CodingKey {
        case id
        case name
        case allowProfilesOutsideOrganization = "allow_profiles_outside_organization"
        case domains
        case metadata
    }
}

/// Convenience alias for a page of Organizations.
public typealias OrganizationPage = Page<Organization>
