import { describe, it, expect } from 'vitest';
import * as fs from 'node:fs/promises';
import * as os from 'node:os';
import * as path from 'node:path';
import {
  computeStalePaths,
  MANIFEST_FILENAME,
  pruneStaleFiles,
  readManifest,
  writeManifest,
} from '../../src/engine/manifest.js';

async function tmp(): Promise<string> {
  return fs.mkdtemp(path.join(os.tmpdir(), 'oagen-manifest-'));
}

describe('manifest read/write', () => {
  it('writes a manifest with sorted, deduped paths', async () => {
    const dir = await tmp();
    try {
      await writeManifest(dir, { language: 'python', files: ['b.py', 'a.py', 'b.py', 'c.py'] });
      const raw = await fs.readFile(path.join(dir, MANIFEST_FILENAME), 'utf-8');
      const parsed = JSON.parse(raw);
      expect(parsed.files).toEqual(['a.py', 'b.py', 'c.py']);
      expect(parsed.language).toBe('python');
      expect(parsed.version).toBe(1);
      expect(typeof parsed.generatedAt).toBe('string');
    } finally {
      await fs.rm(dir, { recursive: true });
    }
  });

  it('readManifest returns null when file is absent', async () => {
    const dir = await tmp();
    try {
      expect(await readManifest(dir)).toBeNull();
    } finally {
      await fs.rm(dir, { recursive: true });
    }
  });

  it('readManifest returns null on malformed JSON', async () => {
    const dir = await tmp();
    try {
      await fs.writeFile(path.join(dir, MANIFEST_FILENAME), '{ not json');
      expect(await readManifest(dir)).toBeNull();
    } finally {
      await fs.rm(dir, { recursive: true });
    }
  });

  it('readManifest returns null when required fields are missing', async () => {
    const dir = await tmp();
    try {
      await fs.writeFile(path.join(dir, MANIFEST_FILENAME), JSON.stringify({ version: 1, files: ['a.py'] }));
      expect(await readManifest(dir)).toBeNull();
    } finally {
      await fs.rm(dir, { recursive: true });
    }
  });

  it('round-trips language and files list', async () => {
    const dir = await tmp();
    try {
      await writeManifest(dir, { language: 'node', files: ['src/index.ts', 'src/client.ts'] });
      const got = await readManifest(dir);
      expect(got).not.toBeNull();
      expect(got!.language).toBe('node');
      expect(got!.files).toEqual(['src/client.ts', 'src/index.ts']);
    } finally {
      await fs.rm(dir, { recursive: true });
    }
  });
});

describe('computeStalePaths', () => {
  it('returns files present in prev but absent from current', () => {
    const prev = {
      version: 1,
      language: 'python',
      generatedAt: '2026-01-01T00:00:00.000Z',
      files: ['a.py', 'b.py', 'c.py'],
    };
    expect(computeStalePaths(prev, ['a.py', 'c.py', 'd.py'])).toEqual(['b.py']);
  });

  it('returns empty when nothing is stale', () => {
    const prev = {
      version: 1,
      language: 'python',
      generatedAt: '2026-01-01T00:00:00.000Z',
      files: ['a.py'],
    };
    expect(computeStalePaths(prev, ['a.py', 'b.py'])).toEqual([]);
  });

  it('sorts the result', () => {
    const prev = {
      version: 1,
      language: 'python',
      generatedAt: '2026-01-01T00:00:00.000Z',
      files: ['zeta.py', 'alpha.py', 'mu.py'],
    };
    expect(computeStalePaths(prev, [])).toEqual(['alpha.py', 'mu.py', 'zeta.py']);
  });
});

describe('pruneStaleFiles', () => {
  const header = '# auto-generated by oagen';

  it('deletes files that start with the header', async () => {
    const dir = await tmp();
    try {
      await fs.writeFile(path.join(dir, 'gen.py'), `${header}\n\nclass Foo: pass\n`);
      const result = await pruneStaleFiles(dir, ['gen.py'], { header });
      expect(result.pruned).toEqual(['gen.py']);
      expect(result.preserved).toEqual([]);
      await expect(fs.stat(path.join(dir, 'gen.py'))).rejects.toThrow();
    } finally {
      await fs.rm(dir, { recursive: true });
    }
  });

  it('preserves files missing the header', async () => {
    const dir = await tmp();
    try {
      await fs.writeFile(path.join(dir, 'hand.py'), 'class HandWritten: pass\n');
      const result = await pruneStaleFiles(dir, ['hand.py'], { header });
      expect(result.pruned).toEqual([]);
      expect(result.preserved).toEqual(['hand.py']);
      await expect(fs.stat(path.join(dir, 'hand.py'))).resolves.toBeTruthy();
    } finally {
      await fs.rm(dir, { recursive: true });
    }
  });

  it('reports paths that do not exist on disk', async () => {
    const dir = await tmp();
    try {
      const result = await pruneStaleFiles(dir, ['missing.py'], { header });
      expect(result.missing).toEqual(['missing.py']);
      expect(result.pruned).toEqual([]);
    } finally {
      await fs.rm(dir, { recursive: true });
    }
  });

  it('removes empty parent directories after deletion', async () => {
    const dir = await tmp();
    try {
      const nested = path.join(dir, 'deep', 'nest');
      await fs.mkdir(nested, { recursive: true });
      await fs.writeFile(path.join(nested, 'gen.py'), `${header}\n`);
      const result = await pruneStaleFiles(dir, ['deep/nest/gen.py'], { header });
      expect(result.pruned).toEqual(['deep/nest/gen.py']);
      await expect(fs.stat(path.join(dir, 'deep'))).rejects.toThrow();
    } finally {
      await fs.rm(dir, { recursive: true });
    }
  });

  it('leaves parent directory alone when siblings remain', async () => {
    const dir = await tmp();
    try {
      const nest = path.join(dir, 'models');
      await fs.mkdir(nest, { recursive: true });
      await fs.writeFile(path.join(nest, 'gen.py'), `${header}\n`);
      await fs.writeFile(path.join(nest, 'keep.py'), 'keep\n');
      await pruneStaleFiles(dir, ['models/gen.py'], { header });
      await expect(fs.stat(nest)).resolves.toBeTruthy();
      await expect(fs.stat(path.join(nest, 'keep.py'))).resolves.toBeTruthy();
    } finally {
      await fs.rm(dir, { recursive: true });
    }
  });

  it('deletes without guard when header is omitted', async () => {
    const dir = await tmp();
    try {
      await fs.writeFile(path.join(dir, 'fixture.json'), '{"foo": 1}');
      const result = await pruneStaleFiles(dir, ['fixture.json']);
      expect(result.pruned).toEqual(['fixture.json']);
    } finally {
      await fs.rm(dir, { recursive: true });
    }
  });
});
