import { describe, it, expect } from 'vitest';
import { mergeIntoExisting, extractTopLevelNames } from '../../src/engine/merger.js';

describe('extractTopLevelNames', () => {
  it('extracts interface names from TypeScript', async () => {
    const source = `
export interface Organization {
  id: string;
  name: string;
}

export interface User {
  id: string;
  email: string;
}
`;
    const names = await extractTopLevelNames(source, 'node');
    expect(names).toContain('Organization');
    expect(names).toContain('User');
  });

  it('extracts class, enum, and type alias names', async () => {
    const source = `
export class WorkOS {
  constructor() {}
}

export enum Status {
  Active = 'active',
  Inactive = 'inactive',
}

export type Role = 'admin' | 'user';

export const VERSION = '1.0.0';
`;
    const names = await extractTopLevelNames(source, 'node');
    expect(names).toContain('WorkOS');
    expect(names).toContain('Status');
    expect(names).toContain('Role');
    expect(names).toContain('VERSION');
  });

  it('handles export-from statements', async () => {
    const source = `
export * from './models.js';
export { WorkOS } from './client.js';
`;
    const names = await extractTopLevelNames(source, 'node');
    // Export-from lines get a synthetic name based on source
    expect(names.size).toBeGreaterThan(0);
  });
});

describe('mergeIntoExisting', () => {
  const header = '// Auto-generated by oagen. Do not edit.';

  it('appends new interfaces that do not exist', async () => {
    const existing = `
export interface Organization {
  id: string;
  name: string;
}
`;
    const generated = `
${header}

export interface Organization {
  id: string;
  name: string;
}

export interface User {
  id: string;
  email: string;
}
`;

    const result = await mergeIntoExisting(existing, generated, 'node', header);

    expect(result.changed).toBe(true);
    expect(result.added).toBe(1);
    expect(result.preserved).toBe(1); // Organization was preserved
    expect(result.content).toContain('interface Organization');
    expect(result.content).toContain('interface User');
  });

  it('does not modify existing interfaces', async () => {
    const existing = `
export interface Organization {
  id: string;
  name: string;
  customField: boolean;
}
`;
    const generated = `
${header}

export interface Organization {
  id: string;
  name: string;
}
`;

    const result = await mergeIntoExisting(existing, generated, 'node', header);

    expect(result.changed).toBe(false);
    expect(result.added).toBe(0);
    // The existing file should be untouched — customField preserved
    expect(result.content).toContain('customField: boolean');
  });

  it('returns unchanged when all symbols exist', async () => {
    const existing = `
export interface Foo { id: string; }
export interface Bar { name: string; }
`;
    const generated = `
${header}

export interface Foo { id: string; }
export interface Bar { name: string; }
`;

    const result = await mergeIntoExisting(existing, generated, 'node', header);
    expect(result.changed).toBe(false);
    expect(result.added).toBe(0);
    expect(result.preserved).toBe(2);
  });

  it('adds header if not present in existing file', async () => {
    const existing = `export interface Foo { id: string; }`;
    const generated = `
${header}

export interface Bar { name: string; }
`;

    const result = await mergeIntoExisting(existing, generated, 'node', header);
    expect(result.content).toContain(header);
    expect(result.content).toContain('interface Bar');
  });

  it('handles barrel export lines', async () => {
    const existing = `
export * from './organizations/interfaces/index.js';
export * from './common/exceptions/index.js';
`;
    const generated = `
${header}

export * from './organizations/interfaces/index.js';
export * from './common/exceptions/index.js';
export * from './sso/interfaces/index.js';
`;

    const result = await mergeIntoExisting(existing, generated, 'node', header);
    expect(result.changed).toBe(true);
    expect(result.content).toContain("export * from './sso/interfaces/index.js'");
    // Existing exports still there
    expect(result.content).toContain("export * from './organizations/interfaces/index.js'");
  });
});
