import { describe, it, expect } from 'vitest';
import { mergeIntoExisting, extractTopLevelNames, hasGrammar } from '../../src/engine/merger.js';

describe('extractTopLevelNames', () => {
  it('reports node merge grammar availability', () => {
    expect(hasGrammar('node')).toBe(true);
  });

  it('extracts interface names from TypeScript', async () => {
    const source = `
export interface Organization {
  id: string;
  name: string;
}

export interface User {
  id: string;
  email: string;
}
`;
    const names = await extractTopLevelNames(source, 'node');
    expect(names).toContain('Organization');
    expect(names).toContain('User');
  });

  it('extracts class, enum, and type alias names', async () => {
    const source = `
export class WorkOS {
  constructor() {}
}

export enum Status {
  Active = 'active',
  Inactive = 'inactive',
}

export type Role = 'admin' | 'user';

export const VERSION = '1.0.0';
`;
    const names = await extractTopLevelNames(source, 'node');
    expect(names).toContain('WorkOS');
    expect(names).toContain('Status');
    expect(names).toContain('Role');
    expect(names).toContain('VERSION');
  });

  it('handles export-from statements', async () => {
    const source = `
export * from './models.js';
export { WorkOS } from './client.js';
`;
    const names = await extractTopLevelNames(source, 'node');
    // Export-from lines get a synthetic name based on source
    expect(names.size).toBeGreaterThan(0);
  });

  it('extracts class and module names from Ruby', async () => {
    const source = `
require_relative 'client'

module WorkOS
end

class User
end
`;
    const names = await extractTopLevelNames(source, 'ruby');
    expect(names).toContain('WorkOS');
    expect(names).toContain('User');
  });

  it('extracts class and function names from Python', async () => {
    const source = `
import os
from workos.user import User

class Client:
    pass

def helper():
    return 1
`;
    const names = await extractTopLevelNames(source, 'python');
    expect(names).toContain('Client');
    expect(names).toContain('helper');
  });

  it('extracts class and function names from PHP', async () => {
    const source = `
<?php

namespace WorkOS;

use WorkOS\\User;

class Client {}

function helper() {}
`;
    const names = await extractTopLevelNames(source, 'php');
    expect(names).toContain('Client');
    expect(names).toContain('helper');
  });

  it('extracts function and method keys from Go', async () => {
    const source = `
package workos

import "fmt"

type Client struct{}

func helper() {}

func (c *Client) Get() {}
`;
    const names = await extractTopLevelNames(source, 'go');
    expect(names).toContain('helper');
    expect(names).toContain('method:Client.Get');
  });

  it('extracts function and impl keys from Rust', async () => {
    const source = `
use crate::models::User;

pub struct Client {}

pub fn helper() {}

impl Client {
  pub fn get(&self) {}
}
`;
    const names = await extractTopLevelNames(source, 'rust');
    expect(names).toContain('Client');
    expect(names).toContain('helper');
    expect(names).toContain('impl:Client');
  });
});

describe('mergeIntoExisting', () => {
  const header = '// Auto-generated by oagen. Do not edit.';
  const rubyHeader = '# Auto-generated by oagen. Do not edit.';

  it('appends new interfaces that do not exist', async () => {
    const existing = `
export interface Organization {
  id: string;
  name: string;
}
`;
    const generated = `
${header}

export interface Organization {
  id: string;
  name: string;
}

export interface User {
  id: string;
  email: string;
}
`;

    const result = await mergeIntoExisting(existing, generated, 'node', header);

    expect(result.changed).toBe(true);
    expect(result.added).toBe(1);
    expect(result.preserved).toBe(1); // Organization was preserved
    expect(result.content).toContain('interface Organization');
    expect(result.content).toContain('interface User');
  });

  it('does not modify existing interfaces', async () => {
    const existing = `
export interface Organization {
  id: string;
  name: string;
  customField: boolean;
}
`;
    const generated = `
${header}

export interface Organization {
  id: string;
  name: string;
}
`;

    const result = await mergeIntoExisting(existing, generated, 'node', header);

    expect(result.changed).toBe(false);
    expect(result.added).toBe(0);
    // The existing file should be untouched — customField preserved
    expect(result.content).toContain('customField: boolean');
  });

  it('returns unchanged when all symbols exist', async () => {
    const existing = `
export interface Foo { id: string; }
export interface Bar { name: string; }
`;
    const generated = `
${header}

export interface Foo { id: string; }
export interface Bar { name: string; }
`;

    const result = await mergeIntoExisting(existing, generated, 'node', header);
    expect(result.changed).toBe(false);
    expect(result.added).toBe(0);
    expect(result.preserved).toBe(2);
  });

  it('does not prepend header to existing hand-written files', async () => {
    const existing = `export interface Foo { id: string; }`;
    const generated = `
${header}

export interface Bar { name: string; }
`;

    const result = await mergeIntoExisting(existing, generated, 'node', header);
    expect(result.content).not.toMatch(/^\/\/ This file is auto-generated/);
    expect(result.content).toContain('interface Bar');
  });

  it('includes new imports not present in existing file', async () => {
    const existing = `
import { Foo } from './foo';

export interface Foo {
  id: string;
}
`;
    const generated = `
${header}

import { Foo } from './foo.js';
import { Bar } from './bar.js';

export interface Foo {
  id: string;
}

export interface Baz {
  name: string;
}
`;

    const result = await mergeIntoExisting(existing, generated, 'node', header);
    expect(result.changed).toBe(true);
    // Bar import is new — should be included
    expect(result.content).toContain("import { Bar } from './bar.js'");
    // Foo import already exists (normalized) — should not be duplicated
    expect(result.content).toContain('interface Baz');
  });

  it('deduplicates imports with .js extension differences', async () => {
    const existing = `
import { Foo } from './foo';

export interface Foo {
  id: string;
}
`;
    const generated = `
${header}

import { Foo } from './foo.js';

export interface Foo {
  id: string;
}
`;

    const result = await mergeIntoExisting(existing, generated, 'node', header);
    expect(result.changed).toBe(false);
    expect(result.added).toBe(0);
  });

  it('does not add imports when no new symbols need them', async () => {
    const existing = `
import { Foo } from './foo';

export interface Foo { id: string; }
export interface Bar { name: string; }
`;
    const generated = `
${header}

import { Foo } from './foo.js';
import { Baz } from './baz.js';

export interface Foo { id: string; }
export interface Bar { name: string; }
`;

    const result = await mergeIntoExisting(existing, generated, 'node', header);
    // All symbols exist, but Baz import is new — should still be added since
    // the merger doesn't analyze import usage, just deduplicates
    expect(result.changed).toBe(true);
    expect(result.content).toContain("import { Baz } from './baz.js'");
  });

  it('handles barrel export lines', async () => {
    const existing = `
export * from './organizations/interfaces/index.js';
export * from './common/exceptions/index.js';
`;
    const generated = `
${header}

export * from './organizations/interfaces/index.js';
export * from './common/exceptions/index.js';
export * from './sso/interfaces/index.js';
`;

    const result = await mergeIntoExisting(existing, generated, 'node', header);
    expect(result.changed).toBe(true);
    expect(result.content).toContain("export * from './sso/interfaces/index.js'");
    // Existing exports still there
    expect(result.content).toContain("export * from './organizations/interfaces/index.js'");
  });

  it('merges Ruby require_relative lines additively', async () => {
    const existing = `
require_relative 'client'

class Client
end
`;
    const generated = `
${rubyHeader}

require_relative 'client'
require_relative 'user'

class Client
end

class User
end
`;

    const result = await mergeIntoExisting(existing, generated, 'ruby', rubyHeader);
    expect(result.changed).toBe(true);
    expect(result.content).toContain("require_relative 'user'");
    expect(result.content.match(/require_relative 'client'/g)).toHaveLength(1);
    expect(result.content).toContain('class User');
  });

  it('does not duplicate an existing Ruby class', async () => {
    const existing = `
class User
  def initialize; end
end
`;
    const generated = `
${rubyHeader}

class User
end
`;

    const result = await mergeIntoExisting(existing, generated, 'ruby', rubyHeader);
    expect(result.changed).toBe(false);
    expect(result.added).toBe(0);
    expect(result.content).toContain('def initialize');
  });

  it('appends new Ruby modules', async () => {
    const existing = `
module WorkOS
end
`;
    const generated = `
${rubyHeader}

module WorkOS
end

module Types
end
`;

    const result = await mergeIntoExisting(existing, generated, 'ruby', rubyHeader);
    expect(result.changed).toBe(true);
    expect(result.content).toContain('module Types');
  });

  it('merges Python imports and additive classes', async () => {
    const pythonHeader = '# Auto-generated by oagen. Do not edit.';
    const existing = `
import os

class Client:
    pass
`;
    const generated = `
${pythonHeader}

import os
from workos.user import User

class Client:
    pass

class User:
    pass
`;

    const result = await mergeIntoExisting(existing, generated, 'python', pythonHeader);
    expect(result.changed).toBe(true);
    expect(result.content).toContain('from workos.user import User');
    expect(result.content.match(/import os/g)).toHaveLength(1);
    expect(result.content).toContain('class User');
  });

  it('does not duplicate an existing Python function', async () => {
    const pythonHeader = '# Auto-generated by oagen. Do not edit.';
    const existing = `
def helper():
    return 1
`;
    const generated = `
${pythonHeader}

def helper():
    return 2
`;

    const result = await mergeIntoExisting(existing, generated, 'python', pythonHeader);
    expect(result.changed).toBe(false);
    expect(result.added).toBe(0);
    expect(result.content).toContain('return 1');
  });

  it('merges PHP imports and additive declarations', async () => {
    const phpHeader = '// Auto-generated by oagen. Do not edit.';
    const existing = `
<?php

namespace WorkOS;

use WorkOS\\Client;

class Client {}
`;
    const generated = `
${phpHeader}

<?php

namespace WorkOS;

use WorkOS\\Client;
use WorkOS\\User;

class Client {}

class User {}
`;

    const result = await mergeIntoExisting(existing, generated, 'php', phpHeader);
    expect(result.changed).toBe(true);
    expect(result.content).toContain('use WorkOS\\User;');
    expect(result.content.match(/use WorkOS\\Client;/g)).toHaveLength(1);
    expect(result.content).toContain('class User {}');
  });

  it('does not duplicate an existing PHP function', async () => {
    const phpHeader = '// Auto-generated by oagen. Do not edit.';
    const existing = `
<?php

function helper() {
  return 1;
}
`;
    const generated = `
${phpHeader}

<?php

function helper() {
  return 2;
}
`;

    const result = await mergeIntoExisting(existing, generated, 'php', phpHeader);
    expect(result.changed).toBe(false);
    expect(result.added).toBe(0);
    expect(result.content).toContain('return 1;');
  });

  it('merges Go grouped imports and additive methods', async () => {
    const existing = `
package workos

import (
  "fmt"
)

type Client struct{}

func (c *Client) Get() {}
`;
    const generated = `
${header}

package workos

import (
  "fmt"
  "context"
)

type Client struct{}

func helper() {}

func (c *Client) Get() {}
`;

    const result = await mergeIntoExisting(existing, generated, 'go', header);
    expect(result.changed).toBe(true);
    expect(result.content).toContain('import "context"');
    expect(result.content.match(/package workos/g)).toHaveLength(1);
    expect(result.content).toContain('func helper() {}');
  });

  it('does not duplicate an existing Go method with the same receiver', async () => {
    const existing = `
package workos

type Client struct{}

func (c *Client) Get() {
  println("old")
}
`;
    const generated = `
${header}

package workos

type Client struct{}

func (c *Client) Get() {}
`;

    const result = await mergeIntoExisting(existing, generated, 'go', header);
    expect(result.changed).toBe(false);
    expect(result.content).toContain('println("old")');
  });

  it('merges Rust imports and additive impl blocks', async () => {
    const existing = `
use crate::models::User;

pub struct Client {}

impl Client {
  pub fn get(&self) {}
}
`;
    const generated = `
${header}

use crate::models::User;
use std::fmt;

pub struct Client {}

impl Client {
  pub fn get(&self) {}
}

impl Display for Client {
  fn fmt(&self, f: &mut Formatter<'_>) {}
}
`;

    const result = await mergeIntoExisting(existing, generated, 'rust', header);
    expect(result.changed).toBe(true);
    expect(result.content).toContain('use std::fmt;');
    expect(result.content).toContain('impl Display for Client');
  });

  it('does not duplicate an existing Rust impl block', async () => {
    const existing = `
impl Client {
  pub fn get(&self) {
    println!("old");
  }
}
`;
    const generated = `
${header}

impl Client {
  pub fn get(&self) {}
}
`;

    const result = await mergeIntoExisting(existing, generated, 'rust', header);
    expect(result.changed).toBe(false);
    expect(result.content).toContain('println!("old");');
  });
});
