import { describe, it, expect } from 'vitest';
import { mergeIntoExisting, extractTopLevelNames, hasGrammar } from '../../src/engine/merger.js';

describe('extractTopLevelNames', () => {
  it('reports node merge grammar availability', () => {
    expect(hasGrammar('node')).toBe(true);
  });

  it('extracts interface names from TypeScript', async () => {
    const source = `
export interface Organization {
  id: string;
  name: string;
}

export interface User {
  id: string;
  email: string;
}
`;
    const names = await extractTopLevelNames(source, 'node');
    expect(names).toContain('Organization');
    expect(names).toContain('User');
  });

  it('extracts class, enum, and type alias names', async () => {
    const source = `
export class WorkOS {
  constructor() {}
}

export enum Status {
  Active = 'active',
  Inactive = 'inactive',
}

export type Role = 'admin' | 'user';

export const VERSION = '1.0.0';
`;
    const names = await extractTopLevelNames(source, 'node');
    expect(names).toContain('WorkOS');
    expect(names).toContain('Status');
    expect(names).toContain('Role');
    expect(names).toContain('VERSION');
  });

  it('handles export-from statements', async () => {
    const source = `
export * from './models.js';
export { WorkOS } from './client.js';
`;
    const names = await extractTopLevelNames(source, 'node');
    // Export-from lines get a synthetic name based on source
    expect(names.size).toBeGreaterThan(0);
  });

  it('extracts class and module names from Ruby', async () => {
    const source = `
require_relative 'client'

module WorkOS
end

class User
end
`;
    const names = await extractTopLevelNames(source, 'ruby');
    expect(names).toContain('WorkOS');
    expect(names).toContain('User');
  });
});

describe('mergeIntoExisting', () => {
  const header = '// Auto-generated by oagen. Do not edit.';
  const rubyHeader = '# Auto-generated by oagen. Do not edit.';

  it('appends new interfaces that do not exist', async () => {
    const existing = `
export interface Organization {
  id: string;
  name: string;
}
`;
    const generated = `
${header}

export interface Organization {
  id: string;
  name: string;
}

export interface User {
  id: string;
  email: string;
}
`;

    const result = await mergeIntoExisting(existing, generated, 'node', header);

    expect(result.changed).toBe(true);
    expect(result.added).toBe(1);
    expect(result.preserved).toBe(1); // Organization was preserved
    expect(result.content).toContain('interface Organization');
    expect(result.content).toContain('interface User');
  });

  it('does not modify existing interfaces', async () => {
    const existing = `
export interface Organization {
  id: string;
  name: string;
  customField: boolean;
}
`;
    const generated = `
${header}

export interface Organization {
  id: string;
  name: string;
}
`;

    const result = await mergeIntoExisting(existing, generated, 'node', header);

    expect(result.changed).toBe(false);
    expect(result.added).toBe(0);
    // The existing file should be untouched — customField preserved
    expect(result.content).toContain('customField: boolean');
  });

  it('returns unchanged when all symbols exist', async () => {
    const existing = `
export interface Foo { id: string; }
export interface Bar { name: string; }
`;
    const generated = `
${header}

export interface Foo { id: string; }
export interface Bar { name: string; }
`;

    const result = await mergeIntoExisting(existing, generated, 'node', header);
    expect(result.changed).toBe(false);
    expect(result.added).toBe(0);
    expect(result.preserved).toBe(2);
  });

  it('does not prepend header to existing hand-written files', async () => {
    const existing = `export interface Foo { id: string; }`;
    const generated = `
${header}

export interface Bar { name: string; }
`;

    const result = await mergeIntoExisting(existing, generated, 'node', header);
    expect(result.content).not.toMatch(/^\/\/ This file is auto-generated/);
    expect(result.content).toContain('interface Bar');
  });

  it('includes new imports not present in existing file', async () => {
    const existing = `
import { Foo } from './foo';

export interface Foo {
  id: string;
}
`;
    const generated = `
${header}

import { Foo } from './foo.js';
import { Bar } from './bar.js';

export interface Foo {
  id: string;
}

export interface Baz {
  name: string;
}
`;

    const result = await mergeIntoExisting(existing, generated, 'node', header);
    expect(result.changed).toBe(true);
    // Bar import is new — should be included
    expect(result.content).toContain("import { Bar } from './bar.js'");
    // Foo import already exists (normalized) — should not be duplicated
    expect(result.content).toContain('interface Baz');
  });

  it('deduplicates imports with .js extension differences', async () => {
    const existing = `
import { Foo } from './foo';

export interface Foo {
  id: string;
}
`;
    const generated = `
${header}

import { Foo } from './foo.js';

export interface Foo {
  id: string;
}
`;

    const result = await mergeIntoExisting(existing, generated, 'node', header);
    expect(result.changed).toBe(false);
    expect(result.added).toBe(0);
  });

  it('does not add imports when no new symbols need them', async () => {
    const existing = `
import { Foo } from './foo';

export interface Foo { id: string; }
export interface Bar { name: string; }
`;
    const generated = `
${header}

import { Foo } from './foo.js';
import { Baz } from './baz.js';

export interface Foo { id: string; }
export interface Bar { name: string; }
`;

    const result = await mergeIntoExisting(existing, generated, 'node', header);
    // All symbols exist, but Baz import is new — should still be added since
    // the merger doesn't analyze import usage, just deduplicates
    expect(result.changed).toBe(true);
    expect(result.content).toContain("import { Baz } from './baz.js'");
  });

  it('handles barrel export lines', async () => {
    const existing = `
export * from './organizations/interfaces/index.js';
export * from './common/exceptions/index.js';
`;
    const generated = `
${header}

export * from './organizations/interfaces/index.js';
export * from './common/exceptions/index.js';
export * from './sso/interfaces/index.js';
`;

    const result = await mergeIntoExisting(existing, generated, 'node', header);
    expect(result.changed).toBe(true);
    expect(result.content).toContain("export * from './sso/interfaces/index.js'");
    // Existing exports still there
    expect(result.content).toContain("export * from './organizations/interfaces/index.js'");
  });

  it('merges Ruby require_relative lines additively', async () => {
    const existing = `
require_relative 'client'

class Client
end
`;
    const generated = `
${rubyHeader}

require_relative 'client'
require_relative 'user'

class Client
end

class User
end
`;

    const result = await mergeIntoExisting(existing, generated, 'ruby', rubyHeader);
    expect(result.changed).toBe(true);
    expect(result.content).toContain("require_relative 'user'");
    expect(result.content.match(/require_relative 'client'/g)).toHaveLength(1);
    expect(result.content).toContain('class User');
  });

  it('does not duplicate an existing Ruby class', async () => {
    const existing = `
class User
  def initialize; end
end
`;
    const generated = `
${rubyHeader}

class User
end
`;

    const result = await mergeIntoExisting(existing, generated, 'ruby', rubyHeader);
    expect(result.changed).toBe(false);
    expect(result.added).toBe(0);
    expect(result.content).toContain('def initialize');
  });

  it('appends new Ruby modules', async () => {
    const existing = `
module WorkOS
end
`;
    const generated = `
${rubyHeader}

module WorkOS
end

module Types
end
`;

    const result = await mergeIntoExisting(existing, generated, 'ruby', rubyHeader);
    expect(result.changed).toBe(true);
    expect(result.content).toContain('module Types');
  });
});
