import { describe, it, expect } from 'vitest';
import { writeFiles } from '../../src/engine/writer.js';
import * as fs from 'node:fs/promises';
import * as os from 'node:os';
import * as path from 'node:path';

describe('@oagen-ignore-file', () => {
  const header = '// Auto-generated by oagen. Do not edit.';

  it('skips file with @oagen-ignore-file in existing content', async () => {
    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'oagen-test-'));
    try {
      const filePath = path.join(tmpDir, 'client.ts');
      await fs.writeFile(filePath, '// @oagen-ignore-file\nexport class Client {}', 'utf-8');

      const result = await writeFiles(
        [{ path: 'client.ts', content: 'export class Client { newMethod() {} }' }],
        tmpDir,
        { language: 'node', header },
      );

      expect(result.ignored).toEqual(['client.ts']);
      const content = await fs.readFile(filePath, 'utf-8');
      expect(content).toBe('// @oagen-ignore-file\nexport class Client {}');
    } finally {
      await fs.rm(tmpDir, { recursive: true });
    }
  });

  it('writes new file even if generated content has @oagen-ignore-file', async () => {
    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'oagen-test-'));
    try {
      const result = await writeFiles(
        [{ path: 'client.ts', content: '// @oagen-ignore-file\nexport class Client {}' }],
        tmpDir,
        { language: 'node', header },
      );

      expect(result.written).toEqual(['client.ts']);
      expect(result.ignored).toEqual([]);
    } finally {
      await fs.rm(tmpDir, { recursive: true });
    }
  });

  it('does not affect other files in same batch', async () => {
    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'oagen-test-'));
    try {
      const ignoredPath = path.join(tmpDir, 'ignored.ts');
      await fs.writeFile(ignoredPath, '// @oagen-ignore-file\nexport class Ignored {}', 'utf-8');

      const result = await writeFiles(
        [
          { path: 'ignored.ts', content: 'export class Ignored { updated() {} }' },
          { path: 'normal.ts', content: 'export class Normal {}' },
        ],
        tmpDir,
        { language: 'node', header },
      );

      expect(result.ignored).toEqual(['ignored.ts']);
      expect(result.written).toEqual(['normal.ts']);
      const ignoredContent = await fs.readFile(ignoredPath, 'utf-8');
      expect(ignoredContent).toBe('// @oagen-ignore-file\nexport class Ignored {}');
    } finally {
      await fs.rm(tmpDir, { recursive: true });
    }
  });

  it('works with grammar-backed merge files', async () => {
    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'oagen-test-'));
    try {
      const filePath = path.join(tmpDir, 'service.ts');
      await fs.writeFile(
        filePath,
        `${header}\n\n// @oagen-ignore-file\nexport class Service {\n  get() {}\n}\n`,
        'utf-8',
      );

      const result = await writeFiles(
        [
          {
            path: 'service.ts',
            content: `${header}\n\nexport class Service {\n  get() {}\n  post() {}\n}\n`,
          },
        ],
        tmpDir,
        { language: 'node', header },
      );

      expect(result.ignored).toEqual(['service.ts']);
      const content = await fs.readFile(filePath, 'utf-8');
      expect(content).toContain('@oagen-ignore-file');
      expect(content).not.toContain('post');
    } finally {
      await fs.rm(tmpDir, { recursive: true });
    }
  });
});
