import { describe, it, expect } from 'vitest';
import { writeFiles, overwriteWithPreservedRegions } from '../../src/engine/writer.js';
import * as fs from 'node:fs/promises';
import * as os from 'node:os';
import * as path from 'node:path';

describe('@oagen-ignore-file', () => {
  const header = '// Auto-generated by oagen. Do not edit.';

  it('skips file with @oagen-ignore-file in existing content', async () => {
    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'oagen-test-'));
    try {
      const filePath = path.join(tmpDir, 'client.ts');
      await fs.writeFile(filePath, '// @oagen-ignore-file\nexport class Client {}', 'utf-8');

      const result = await writeFiles(
        [{ path: 'client.ts', content: 'export class Client { newMethod() {} }' }],
        tmpDir,
        { language: 'node', header },
      );

      expect(result.ignored).toEqual(['client.ts']);
      const content = await fs.readFile(filePath, 'utf-8');
      expect(content).toBe('// @oagen-ignore-file\nexport class Client {}');
    } finally {
      await fs.rm(tmpDir, { recursive: true });
    }
  });

  it('writes new file even if generated content has @oagen-ignore-file', async () => {
    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'oagen-test-'));
    try {
      const result = await writeFiles(
        [{ path: 'client.ts', content: '// @oagen-ignore-file\nexport class Client {}' }],
        tmpDir,
        { language: 'node', header },
      );

      expect(result.written).toEqual(['client.ts']);
      expect(result.ignored).toEqual([]);
    } finally {
      await fs.rm(tmpDir, { recursive: true });
    }
  });

  it('does not affect other files in same batch', async () => {
    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'oagen-test-'));
    try {
      const ignoredPath = path.join(tmpDir, 'ignored.ts');
      await fs.writeFile(ignoredPath, '// @oagen-ignore-file\nexport class Ignored {}', 'utf-8');

      const result = await writeFiles(
        [
          { path: 'ignored.ts', content: 'export class Ignored { updated() {} }' },
          { path: 'normal.ts', content: 'export class Normal {}' },
        ],
        tmpDir,
        { language: 'node', header },
      );

      expect(result.ignored).toEqual(['ignored.ts']);
      expect(result.written).toEqual(['normal.ts']);
      const ignoredContent = await fs.readFile(ignoredPath, 'utf-8');
      expect(ignoredContent).toBe('// @oagen-ignore-file\nexport class Ignored {}');
    } finally {
      await fs.rm(tmpDir, { recursive: true });
    }
  });

  it('works with grammar-backed merge files', async () => {
    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'oagen-test-'));
    try {
      const filePath = path.join(tmpDir, 'service.ts');
      await fs.writeFile(
        filePath,
        `${header}\n\n// @oagen-ignore-file\nexport class Service {\n  get() {}\n}\n`,
        'utf-8',
      );

      const result = await writeFiles(
        [
          {
            path: 'service.ts',
            content: `${header}\n\nexport class Service {\n  get() {}\n  post() {}\n}\n`,
          },
        ],
        tmpDir,
        { language: 'node', header },
      );

      expect(result.ignored).toEqual(['service.ts']);
      const content = await fs.readFile(filePath, 'utf-8');
      expect(content).toContain('@oagen-ignore-file');
      expect(content).not.toContain('post');
    } finally {
      await fs.rm(tmpDir, { recursive: true });
    }
  });
});

describe('@oagen-ignore-start/end with overwriteExisting', () => {
  it('preserves ignore regions in Python classes during overwrite', async () => {
    const existing = [
      '# This file is auto-generated by oagen. Do not edit.',
      '',
      'from typing import Any, Dict, Optional, Union',
      '',
      '',
      'class Webhooks:',
      '    """Webhooks API resources."""',
      '',
      '    def list(self):',
      '        pass',
      '',
      '    def delete(self):',
      '        pass',
      '',
      '    # @oagen-ignore-start',
      '    def verify_event(self, *, event_body: Union[bytes, str]) -> Dict[str, Any]:',
      '        """Verify and deserialize a webhook event."""',
      '        pass',
      '    # @oagen-ignore-end',
      '',
      '',
      'class AsyncWebhooks:',
      '    """Webhooks API resources (async)."""',
      '',
      '    async def list(self):',
      '        pass',
    ].join('\n');

    const generated = [
      '# This file is auto-generated by oagen. Do not edit.',
      '',
      'from typing import Any, Dict, Optional',
      '',
      '',
      'class Webhooks:',
      '    """Webhooks API resources."""',
      '',
      '    def list(self):',
      '        pass',
      '',
      '    def delete(self):',
      '        pass',
      '',
      '    def create(self):',
      '        pass',
      '',
      '',
      'class AsyncWebhooks:',
      '    """Webhooks API resources (async)."""',
      '',
      '    async def list(self):',
      '        pass',
    ].join('\n');

    const result = await overwriteWithPreservedRegions(existing, generated, 'python');

    // Ignore block is preserved
    expect(result).toContain('@oagen-ignore-start');
    expect(result).toContain('verify_event');
    expect(result).toContain('@oagen-ignore-end');
    // New generated method is present
    expect(result).toContain('def create(self):');
    // Extra import identifier is preserved
    expect(result).toContain('Union');
    // Block is inside Webhooks, not AsyncWebhooks
    const lines = result.split('\n');
    const ignoreStart = lines.findIndex((l) => l.includes('@oagen-ignore-start'));
    const asyncClass = lines.findIndex((l) => l.includes('class AsyncWebhooks'));
    expect(ignoreStart).toBeLessThan(asyncClass);
  });

  it('preserves multiple ignore regions across different classes', async () => {
    const existing = [
      'class SSO:',
      '    def authorize(self): pass',
      '',
      '    # @oagen-ignore-start',
      '    def list_connections(self): pass',
      '    # @oagen-ignore-end',
      '',
      '',
      'class AsyncSSO:',
      '    async def authorize(self): pass',
      '',
      '    # @oagen-ignore-start',
      '    async def list_connections(self): pass',
      '    # @oagen-ignore-end',
    ].join('\n');

    const generated = [
      'class SSO:',
      '    def authorize(self): pass',
      '',
      '',
      'class AsyncSSO:',
      '    async def authorize(self): pass',
    ].join('\n');

    const result = await overwriteWithPreservedRegions(existing, generated, 'python');

    // Both ignore blocks preserved
    const matches = result.match(/@oagen-ignore-start/g);
    expect(matches).toHaveLength(2);
    expect(result).toContain('def list_connections');
    expect(result).toContain('async def list_connections');
  });

  it('preserves extra simple imports needed by ignore regions', async () => {
    const existing = [
      'import hashlib',
      'import hmac',
      'from typing import Optional',
      '',
      'class Webhooks:',
      '    def list(self): pass',
      '',
      '    # @oagen-ignore-start',
      '    def verify(self):',
      '        hmac.new(hashlib.sha256)',
      '    # @oagen-ignore-end',
    ].join('\n');

    const generated = ['from typing import Optional', '', 'class Webhooks:', '    def list(self): pass'].join('\n');

    const result = await overwriteWithPreservedRegions(existing, generated, 'python');

    expect(result).toContain('import hashlib');
    expect(result).toContain('import hmac');
    expect(result).toContain('verify');
  });

  it('preserves extra from-import identifiers', async () => {
    const existing = [
      'from typing import Any, Dict, Optional, Union',
      '',
      'class Foo:',
      '    # @oagen-ignore-start',
      '    def bar(self, x: Union[str, int]): pass',
      '    # @oagen-ignore-end',
    ].join('\n');

    const generated = ['from typing import Any, Dict, Optional', '', 'class Foo:', '    def baz(self): pass'].join(
      '\n',
    );

    const result = await overwriteWithPreservedRegions(existing, generated, 'python');

    expect(result).toContain('Union');
    expect(result).toContain('bar');
    expect(result).toContain('baz');
  });

  it('returns generated content unchanged when no ignore regions exist', async () => {
    const existing = 'class Foo:\n    def old(self): pass\n';
    const generated = 'class Foo:\n    def new(self): pass\n';

    const result = await overwriteWithPreservedRegions(existing, generated, 'python');
    expect(result).toBe(generated);
  });

  it('preserves ignore regions in brace-delimited classes', async () => {
    const existing = [
      'export class Webhooks {',
      '  list() {}',
      '',
      '  // @oagen-ignore-start',
      '  verifyEvent() { return true; }',
      '  // @oagen-ignore-end',
      '}',
    ].join('\n');

    const generated = ['export class Webhooks {', '  list() {}', '  create() {}', '}'].join('\n');

    const result = await overwriteWithPreservedRegions(existing, generated, 'node');

    expect(result).toContain('verifyEvent');
    expect(result).toContain('create');
    // Block should be inside the braces
    const lines = result.split('\n');
    const ignoreIdx = lines.findIndex((l) => l.includes('@oagen-ignore-start'));
    const closingBrace = lines.lastIndexOf('}');
    expect(ignoreIdx).toBeLessThan(closingBrace);
  });

  it('integrates with writeFiles for overwriteExisting files', async () => {
    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'oagen-test-'));
    try {
      const filePath = path.join(tmpDir, '_resource.py');
      await fs.writeFile(
        filePath,
        [
          'from typing import Optional',
          '',
          'class Webhooks:',
          '    def list(self): pass',
          '',
          '    # @oagen-ignore-start',
          '    def verify_event(self): pass',
          '    # @oagen-ignore-end',
        ].join('\n'),
        'utf-8',
      );

      const result = await writeFiles(
        [
          {
            path: '_resource.py',
            content: [
              'from typing import Optional',
              '',
              'class Webhooks:',
              '    def list(self): pass',
              '',
              '    def create(self): pass',
            ].join('\n'),
            overwriteExisting: true,
          },
        ],
        tmpDir,
        { language: 'python' },
      );

      expect(result.written).toContain('_resource.py');
      const content = await fs.readFile(filePath, 'utf-8');
      expect(content).toContain('verify_event');
      expect(content).toContain('@oagen-ignore-start');
      expect(content).toContain('create');
    } finally {
      await fs.rm(tmpDir, { recursive: true });
    }
  });
});
