import { describe, it, expect } from 'vitest';
import { writeFiles, overwriteWithPreservedRegions } from '../../src/engine/writer.js';
import * as fs from 'node:fs/promises';
import * as os from 'node:os';
import * as path from 'node:path';

describe('@oagen-ignore-file', () => {
  const header = '// Auto-generated by oagen. Do not edit.';

  it('skips file with @oagen-ignore-file in existing content', async () => {
    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'oagen-test-'));
    try {
      const filePath = path.join(tmpDir, 'client.ts');
      await fs.writeFile(filePath, '// @oagen-ignore-file\nexport class Client {}', 'utf-8');

      const result = await writeFiles(
        [
          {
            path: 'client.ts',
            content: 'export class Client { newMethod() {} }',
          },
        ],
        tmpDir,
        { language: 'node', header },
      );

      expect(result.ignored).toEqual(['client.ts']);
      const content = await fs.readFile(filePath, 'utf-8');
      expect(content).toBe('// @oagen-ignore-file\nexport class Client {}');
    } finally {
      await fs.rm(tmpDir, { recursive: true });
    }
  });

  it('writes new file even if generated content has @oagen-ignore-file', async () => {
    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'oagen-test-'));
    try {
      const result = await writeFiles(
        [
          {
            path: 'client.ts',
            content: '// @oagen-ignore-file\nexport class Client {}',
          },
        ],
        tmpDir,
        { language: 'node', header },
      );

      expect(result.written).toEqual(['client.ts']);
      expect(result.ignored).toEqual([]);
    } finally {
      await fs.rm(tmpDir, { recursive: true });
    }
  });

  it('does not affect other files in same batch', async () => {
    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'oagen-test-'));
    try {
      const ignoredPath = path.join(tmpDir, 'ignored.ts');
      await fs.writeFile(ignoredPath, '// @oagen-ignore-file\nexport class Ignored {}', 'utf-8');

      const result = await writeFiles(
        [
          {
            path: 'ignored.ts',
            content: 'export class Ignored { updated() {} }',
          },
          { path: 'normal.ts', content: 'export class Normal {}' },
        ],
        tmpDir,
        { language: 'node', header },
      );

      expect(result.ignored).toEqual(['ignored.ts']);
      expect(result.written).toEqual(['normal.ts']);
      const ignoredContent = await fs.readFile(ignoredPath, 'utf-8');
      expect(ignoredContent).toBe('// @oagen-ignore-file\nexport class Ignored {}');
    } finally {
      await fs.rm(tmpDir, { recursive: true });
    }
  });

  it('works with grammar-backed merge files', async () => {
    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'oagen-test-'));
    try {
      const filePath = path.join(tmpDir, 'service.ts');
      await fs.writeFile(
        filePath,
        `${header}\n\n// @oagen-ignore-file\nexport class Service {\n  get() {}\n}\n`,
        'utf-8',
      );

      const result = await writeFiles(
        [
          {
            path: 'service.ts',
            content: `${header}\n\nexport class Service {\n  get() {}\n  post() {}\n}\n`,
          },
        ],
        tmpDir,
        { language: 'node', header },
      );

      expect(result.ignored).toEqual(['service.ts']);
      const content = await fs.readFile(filePath, 'utf-8');
      expect(content).toContain('@oagen-ignore-file');
      expect(content).not.toContain('post');
    } finally {
      await fs.rm(tmpDir, { recursive: true });
    }
  });
});

describe('@oagen-ignore-start/end with overwriteExisting', () => {
  it('preserves ignore regions in Python classes during overwrite', async () => {
    const existing = [
      '# This file is auto-generated by oagen. Do not edit.',
      '',
      'from typing import Any, Dict, Optional, Union',
      '',
      '',
      'class Webhooks:',
      '    """Webhooks API resources."""',
      '',
      '    def list(self):',
      '        pass',
      '',
      '    def delete(self):',
      '        pass',
      '',
      '    # @oagen-ignore-start',
      '    def verify_event(self, *, event_body: Union[bytes, str]) -> Dict[str, Any]:',
      '        """Verify and deserialize a webhook event."""',
      '        pass',
      '    # @oagen-ignore-end',
      '',
      '',
      'class AsyncWebhooks:',
      '    """Webhooks API resources (async)."""',
      '',
      '    async def list(self):',
      '        pass',
    ].join('\n');

    const generated = [
      '# This file is auto-generated by oagen. Do not edit.',
      '',
      'from typing import Any, Dict, Optional',
      '',
      '',
      'class Webhooks:',
      '    """Webhooks API resources."""',
      '',
      '    def list(self):',
      '        pass',
      '',
      '    def delete(self):',
      '        pass',
      '',
      '    def create(self):',
      '        pass',
      '',
      '',
      'class AsyncWebhooks:',
      '    """Webhooks API resources (async)."""',
      '',
      '    async def list(self):',
      '        pass',
    ].join('\n');

    const result = await overwriteWithPreservedRegions(existing, generated, 'python');

    // Ignore block is preserved
    expect(result).toContain('@oagen-ignore-start');
    expect(result).toContain('verify_event');
    expect(result).toContain('@oagen-ignore-end');
    // New generated method is present
    expect(result).toContain('def create(self):');
    // Extra import identifier is preserved
    expect(result).toContain('Union');
    // Block is inside Webhooks, not AsyncWebhooks
    const lines = result.split('\n');
    const ignoreStart = lines.findIndex((l) => l.includes('@oagen-ignore-start'));
    const asyncClass = lines.findIndex((l) => l.includes('class AsyncWebhooks'));
    expect(ignoreStart).toBeLessThan(asyncClass);
  });

  it('preserves hand-written TypeScript imports during overwrite', async () => {
    // When a hand-owned TS file is partially regenerated, named/type-only
    // imports referenced inside @oagen-ignore-start/end regions must be
    // brought along at the top of the file, not appended at the end.
    const existing = [
      'import { deserializeEvent } from "../common/serializers";',
      'import { Event, EventResponse } from "../common/interfaces";',
      'import { SignatureProvider } from "../common/crypto/signature-provider";',
      'import type { WorkOS } from "../workos";',
      '',
      'export class Webhooks {',
      '  constructor(private readonly workos: WorkOS) {}',
      '',
      '  // @oagen-ignore-start',
      '  private _sp?: SignatureProvider;',
      '  async constructEvent(): Promise<Event> {',
      '    const payload: EventResponse = {} as EventResponse;',
      '    return deserializeEvent(payload);',
      '  }',
      '  // @oagen-ignore-end',
      '}',
    ].join('\n');

    const generated = [
      'import type { WorkOS } from "../workos";',
      'import type { Foo } from "./interfaces/foo.interface";',
      '',
      'export class Webhooks {',
      '  constructor(private readonly workos: WorkOS) {}',
      '',
      '  async listFoo(): Promise<Foo> { return {} as Foo; }',
      '}',
    ].join('\n');

    const result = await overwriteWithPreservedRegions(existing, generated, 'node');
    const lines = result.split('\n');

    // Hand-written imports survive.
    expect(result).toContain("import { deserializeEvent } from '../common/serializers';");
    expect(result).toContain("import { Event, EventResponse } from '../common/interfaces';");
    expect(result).toContain("import { SignatureProvider } from '../common/crypto/signature-provider';");

    // …and they land before the class declaration, not after it.
    let lastImportLine = -1;
    for (let i = 0; i < lines.length; i++) {
      if (/^import\b/.test(lines[i].trim())) lastImportLine = i;
    }
    const classLine = lines.findIndex((l: string) => /^export class\b/.test(l.trim()));
    expect(lastImportLine).toBeGreaterThan(-1);
    expect(classLine).toBeGreaterThan(lastImportLine);

    // Generated method and ignore-region body both survive.
    expect(result).toContain('async listFoo()');
    expect(result).toContain('constructEvent()');
  });

  it('preserves hand-written PHP `use` imports during overwrite', async () => {
    // PHP `use Foo\Bar;` and `use Foo\Bar as Baz;` referenced from inside an
    // @oagen-ignore-start/end block must land alongside the other top-level
    // use statements, not be dropped or appended to the end of the file.
    const existing = [
      '<?php',
      '',
      'namespace WorkOS;',
      '',
      'use WorkOS\\Service\\Foo;',
      'use WorkOS\\Passwordless;',
      'use WorkOS\\Vault as VaultAlias;',
      '',
      'class WorkOS {',
      '    // @oagen-ignore-start',
      '    private ?Passwordless $passwordless = null;',
      '    private ?VaultAlias $vault = null;',
      '    // @oagen-ignore-end',
      '}',
    ].join('\n');

    const generated = [
      '<?php',
      '',
      'namespace WorkOS;',
      '',
      'use WorkOS\\Service\\Foo;',
      'use WorkOS\\Service\\Bar;',
      '',
      'class WorkOS {',
      '    private Foo $foo;',
      '    private Bar $bar;',
      '}',
    ].join('\n');

    const result = await overwriteWithPreservedRegions(existing, generated, 'php');
    const lines = result.split('\n');

    // Hand-written namespace imports survive.
    expect(result).toContain('use WorkOS\\Passwordless;');
    expect(result).toContain('use WorkOS\\Vault as VaultAlias;');

    // …and they land before the class declaration, not after it.
    let lastUseLine = -1;
    for (let i = 0; i < lines.length; i++) {
      if (/^use\b/.test(lines[i].trim())) lastUseLine = i;
    }
    const classLine = lines.findIndex((l: string) => /^class\b/.test(l.trim()));
    expect(lastUseLine).toBeGreaterThan(-1);
    expect(classLine).toBeGreaterThan(lastUseLine);

    // Generated method/property and ignore-region body both survive.
    expect(result).toContain('private Foo $foo;');
    expect(result).toContain('private ?Passwordless $passwordless');
  });

  it('preserves hand-written Ruby `require`/`require_relative` during overwrite', async () => {
    const existing = [
      "require 'openssl'",
      "require 'workos/version'",
      "require_relative 'helpers/crypto'",
      '',
      'module WorkOS',
      '  class Webhooks',
      '    # @oagen-ignore-start',
      '    def verify_event(sig:)',
      '      OpenSSL::HMAC.hexdigest("SHA256", "k", sig)',
      '    end',
      '    # @oagen-ignore-end',
      '  end',
      'end',
    ].join('\n');

    const generated = [
      "require 'workos/version'",
      "require 'workos/http_client'",
      '',
      'module WorkOS',
      '  class Webhooks',
      '    def list_endpoints; end',
      '  end',
      'end',
    ].join('\n');

    const result = await overwriteWithPreservedRegions(existing, generated, 'ruby');
    const lines = result.split('\n');

    // Hand-written requires survive.
    expect(result).toContain("require 'openssl'");
    expect(result).toContain("require_relative 'helpers/crypto'");

    // …and they land before the module declaration.
    let lastRequireLine = -1;
    for (let i = 0; i < lines.length; i++) {
      if (/^require(_relative)?\b/.test(lines[i].trim())) lastRequireLine = i;
    }
    const moduleLine = lines.findIndex((l: string) => /^module\b/.test(l.trim()));
    expect(lastRequireLine).toBeGreaterThan(-1);
    expect(moduleLine).toBeGreaterThan(lastRequireLine);

    // Generated method and ignore-region body both survive.
    expect(result).toContain('def list_endpoints');
    expect(result).toContain('def verify_event');
  });

  it('does not duplicate Ruby `require` lines when quote styles differ', async () => {
    // The on-disk file has been reformatted (e.g. by standardrb) to double
    // quotes; the freshly generated content still uses single quotes. The
    // dedup must treat them as the same require.
    const existing = [
      'require "json"',
      '',
      'module WorkOS',
      '  class SSO',
      '    # @oagen-ignore-start',
      '    def helper; end',
      '    # @oagen-ignore-end',
      '  end',
      'end',
    ].join('\n');

    const generated = [
      "require 'json'",
      '',
      'module WorkOS',
      '  class SSO',
      '    def list_connections; end',
      '  end',
      'end',
    ].join('\n');

    const result = await overwriteWithPreservedRegions(existing, generated, 'ruby');
    const requireLines = result.split('\n').filter((l) => /^require\b/.test(l.trim()));
    expect(requireLines).toHaveLength(1);
  });

  it('preserves multiple ignore regions across different classes', async () => {
    const existing = [
      'class SSO:',
      '    def authorize(self): pass',
      '',
      '    # @oagen-ignore-start',
      '    def list_connections(self): pass',
      '    # @oagen-ignore-end',
      '',
      '',
      'class AsyncSSO:',
      '    async def authorize(self): pass',
      '',
      '    # @oagen-ignore-start',
      '    async def list_connections(self): pass',
      '    # @oagen-ignore-end',
    ].join('\n');

    const generated = [
      'class SSO:',
      '    def authorize(self): pass',
      '',
      '',
      'class AsyncSSO:',
      '    async def authorize(self): pass',
    ].join('\n');

    const result = await overwriteWithPreservedRegions(existing, generated, 'python');

    // Both ignore blocks preserved
    const matches = result.match(/@oagen-ignore-start/g);
    expect(matches).toHaveLength(2);
    expect(result).toContain('def list_connections');
    expect(result).toContain('async def list_connections');
  });

  it('preserves extra simple imports needed by ignore regions', async () => {
    const existing = [
      'import hashlib',
      'import hmac',
      'from typing import Optional',
      '',
      'class Webhooks:',
      '    def list(self): pass',
      '',
      '    # @oagen-ignore-start',
      '    def verify(self):',
      '        hmac.new(hashlib.sha256)',
      '    # @oagen-ignore-end',
    ].join('\n');

    const generated = ['from typing import Optional', '', 'class Webhooks:', '    def list(self): pass'].join('\n');

    const result = await overwriteWithPreservedRegions(existing, generated, 'python');

    expect(result).toContain('import hashlib');
    expect(result).toContain('import hmac');
    expect(result).toContain('verify');
  });

  it('preserves extra from-import identifiers', async () => {
    const existing = [
      'from typing import Any, Dict, Optional, Union',
      '',
      'class Foo:',
      '    # @oagen-ignore-start',
      '    def bar(self, x: Union[str, int]): pass',
      '    # @oagen-ignore-end',
    ].join('\n');

    const generated = ['from typing import Any, Dict, Optional', '', 'class Foo:', '    def baz(self): pass'].join(
      '\n',
    );

    const result = await overwriteWithPreservedRegions(existing, generated, 'python');

    expect(result).toContain('Union');
    expect(result).toContain('bar');
    expect(result).toContain('baz');
  });

  it('replaces generated class when ignore block redefines it', async () => {
    const existing = [
      'from dataclasses import dataclass',
      'from typing import Any, Dict',
      'from typing import Optional',
      '',
      '',
      '@dataclass(slots=True)',
      'class Event:',
      '    """An event."""',
      '',
      '    @classmethod',
      '    def from_dict(cls, data): pass',
      '',
      '    def to_dict(self): pass',
      '',
      '',
      '# @oagen-ignore-start',
      '@dataclass(slots=True)',
      'class Event:',
      '    """Real event with fields."""',
      '',
      '    id: str',
      '    event: str',
      '    data: Dict[str, Any]',
      '    created_at: Optional[str] = None',
      '# @oagen-ignore-end',
    ].join('\n');

    const generated = [
      'from dataclasses import dataclass',
      'from typing import Any, Dict',
      '',
      '',
      '@dataclass(slots=True)',
      'class Event:',
      '    """An event."""',
      '',
      '    @classmethod',
      '    def from_dict(cls, data): pass',
      '',
      '    def to_dict(self): pass',
    ].join('\n');

    const result = await overwriteWithPreservedRegions(existing, generated, 'python');

    // Only one Event class definition should exist
    const classCount = (result.match(/^class Event/gm) || []).length;
    expect(classCount).toBe(1);
    // The ignore block version should be the one that remains
    expect(result).toContain('id: str');
    expect(result).toContain('@oagen-ignore-start');
    expect(result).toContain('@oagen-ignore-end');
    // The generated stub should be gone
    expect(result).not.toContain('def from_dict(cls, data): pass');
    // Imports should be preserved
    expect(result).toContain('Optional');
  });

  it('replaces generated class when top-level ignore block defines the same class', async () => {
    // When the existing file has ONLY the ignore block (no generated class above it),
    // the block still replaces the matching generated class.
    const existing = [
      '# This file is auto-generated by oagen. Do not edit.',
      '',
      'from dataclasses import dataclass',
      'from typing import Any, Dict',
      'from typing import Optional',
      '',
      '',
      '# @oagen-ignore-start',
      '@dataclass(slots=True)',
      'class Event:',
      '    """Real event with fields."""',
      '',
      '    id: str',
      '    event: str',
      '    data: Dict[str, Any]',
      '    created_at: Optional[str] = None',
      '# @oagen-ignore-end',
    ].join('\n');

    const generated = [
      '# This file is auto-generated by oagen. Do not edit.',
      '',
      'from dataclasses import dataclass',
      'from typing import Any, Dict',
      '',
      '',
      '@dataclass(slots=True)',
      'class Event:',
      '    """An event."""',
      '',
      '    @classmethod',
      '    def from_dict(cls, data): pass',
      '',
      '    def to_dict(self): pass',
    ].join('\n');

    const result = await overwriteWithPreservedRegions(existing, generated, 'python');

    // Only one Event class definition should exist
    const classCount = (result.match(/^class Event/gm) || []).length;
    expect(classCount).toBe(1);
    // The ignore block version should be the one that remains
    expect(result).toContain('id: str');
    expect(result).toContain('@oagen-ignore-start');
    expect(result).toContain('@oagen-ignore-end');
    // The generated stub should be gone
    expect(result).not.toContain('def from_dict(cls, data): pass');
    // Extra imports should be preserved
    expect(result).toContain('Optional');
  });

  it('returns generated content unchanged when no ignore regions exist', async () => {
    const existing = 'class Foo:\n    def old(self): pass\n';
    const generated = 'class Foo:\n    def new(self): pass\n';

    const result = await overwriteWithPreservedRegions(existing, generated, 'python');
    expect(result).toBe(generated);
  });

  it('preserves ignore regions in brace-delimited classes', async () => {
    const existing = [
      'export class Webhooks {',
      '  list() {}',
      '',
      '  // @oagen-ignore-start',
      '  verifyEvent() { return true; }',
      '  // @oagen-ignore-end',
      '}',
    ].join('\n');

    const generated = ['export class Webhooks {', '  list() {}', '  create() {}', '}'].join('\n');

    const result = await overwriteWithPreservedRegions(existing, generated, 'node');

    expect(result).toContain('verifyEvent');
    expect(result).toContain('create');
    // Block should be inside the braces
    const lines = result.split('\n');
    const ignoreIdx = lines.findIndex((l) => l.includes('@oagen-ignore-start'));
    const closingBrace = lines.lastIndexOf('}');
    expect(ignoreIdx).toBeLessThan(closingBrace);
  });

  it('integrates with writeFiles for overwriteExisting files', async () => {
    const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'oagen-test-'));
    try {
      const filePath = path.join(tmpDir, '_resource.py');
      await fs.writeFile(
        filePath,
        [
          'from typing import Optional',
          '',
          'class Webhooks:',
          '    def list(self): pass',
          '',
          '    # @oagen-ignore-start',
          '    def verify_event(self): pass',
          '    # @oagen-ignore-end',
        ].join('\n'),
        'utf-8',
      );

      const result = await writeFiles(
        [
          {
            path: '_resource.py',
            content: [
              'from typing import Optional',
              '',
              'class Webhooks:',
              '    def list(self): pass',
              '',
              '    def create(self): pass',
            ].join('\n'),
            overwriteExisting: true,
          },
        ],
        tmpDir,
        { language: 'python' },
      );

      expect(result.written).toContain('_resource.py');
      const content = await fs.readFile(filePath, 'utf-8');
      expect(content).toContain('verify_event');
      expect(content).toContain('@oagen-ignore-start');
      expect(content).toContain('create');
    } finally {
      await fs.rm(tmpDir, { recursive: true });
    }
  });

  it('does not splice `import type {` as a Python simple import when existing has multi-line TS type imports', async () => {
    // Regression: the Python simple-import detector matched the first line
    // of a multi-line TS `import type { … }` block (`import type {`), so the
    // bare opener got spliced into the result as if it were a `import json`
    // line. Result: a stranded `import type {` orphan before the value
    // imports, breaking TypeScript parsing.
    const existing = [
      "import type { WorkOS } from '../workos';",
      'import type {',
      '  WebhookEndpoint,',
      '  WebhookEndpointResponse,',
      "} from './interfaces/webhook-endpoint.interface';",
      "import { deserializeEvent } from '../common/serializers';",
      '',
      'export class Webhooks {',
      '  // @oagen-ignore-start',
      '  hand() { deserializeEvent({} as any); }',
      '  // @oagen-ignore-end',
      '}',
    ].join('\n');

    const generated = [
      "import type { WorkOS } from '../workos';",
      "import type { WebhookEndpoint, WebhookEndpointResponse } from './interfaces/webhook-endpoint.interface';",
      '',
      'export class Webhooks {',
      '  list() { return [] as WebhookEndpoint[]; }',
      '}',
    ].join('\n');

    const result = await overwriteWithPreservedRegions(existing, generated, 'node');

    // The bare `import type {` from existing must NOT appear in the result.
    expect(result).not.toMatch(/^\s*import type \{\s*$/m);
    // The hand-written value import survives, on its own line.
    expect(result).toContain("import { deserializeEvent } from '../common/serializers';");
  });

  it('keeps same-line top-level ignore block insertion idempotent', async () => {
    const existing = [
      "import type { WorkOS } from '../workos';",
      '',
      '// @oagen-ignore-start',
      "import type { KeyContext } from './interfaces/key.interface';",
      '// @oagen-ignore-end',
      '// @oagen-ignore-start',
      'interface Decoded {',
      '  iv: Uint8Array;',
      '}',
      '// @oagen-ignore-end',
      '',
      'const helper = 1;',
      '',
      'export class Vault {',
      '  constructor(private readonly workos: WorkOS) {}',
      '}',
    ].join('\n');

    const generated = [
      "import type { WorkOS } from '../workos';",
      '',
      'const helper = 1;',
      '',
      'export class Vault {',
      '  constructor(private readonly workos: WorkOS) {}',
      '}',
    ].join('\n');

    const once = await overwriteWithPreservedRegions(existing, generated, 'node');
    const twice = await overwriteWithPreservedRegions(once, generated, 'node');

    expect(twice).toBe(once);
    expect(once.indexOf('KeyContext')).toBeLessThan(once.indexOf('interface Decoded'));
  });
});

describe('region-protected top-level declarations', () => {
  const header = '// Auto-generated by oagen. Do not edit.';

  it('does not duplicate an interface declared inside an ignore region', async () => {
    const existing = [
      header,
      '',
      '// @oagen-ignore-start',
      'export interface GenerateLink {',
      '  intent: string;',
      '  customField: boolean;',
      '}',
      '// @oagen-ignore-end',
      '',
      'export interface GenerateLinkResponse {',
      '  link: string;',
      '}',
    ].join('\n');

    const generated = [
      header,
      '',
      '/**',
      ' * A portal link request.',
      ' */',
      'export interface GenerateLink {',
      '  intent: string;',
      '}',
      '',
      'export interface GenerateLinkResponse {',
      '  link: string;',
      '}',
    ].join('\n');

    const result = await overwriteWithPreservedRegions(existing, generated, 'node');

    // Only the region-protected declaration should remain
    const count = (result.match(/^export interface GenerateLink \{/gm) || []).length;
    expect(count).toBe(1);
    expect(result).toContain('customField: boolean');
    expect(result).toContain('@oagen-ignore-start');
    // The generated docstring belonged to the dropped declaration
    expect(result).not.toContain('A portal link request.');
    // Unprotected symbol untouched
    const respCount = (result.match(/^export interface GenerateLinkResponse \{/gm) || []).length;
    expect(respCount).toBe(1);
    // Regeneration converges
    const second = await overwriteWithPreservedRegions(result, generated, 'node');
    expect(second).toBe(result);
  });

  it('does not duplicate a type alias declared inside an ignore region', async () => {
    const existing = [
      header,
      '',
      '// @oagen-ignore-start',
      "export type Intent = 'sso' | 'dsync' | 'custom';",
      '// @oagen-ignore-end',
      '',
      'export interface Other {',
      '  id: string;',
      '}',
    ].join('\n');

    const generated = [
      header,
      '',
      "export type Intent = 'sso' | 'dsync';",
      '',
      'export interface Other {',
      '  id: string;',
      '}',
    ].join('\n');

    const result = await overwriteWithPreservedRegions(existing, generated, 'node');

    const count = (result.match(/^export type Intent /gm) || []).length;
    expect(count).toBe(1);
    expect(result).toContain("'custom'");
    const second = await overwriteWithPreservedRegions(result, generated, 'node');
    expect(second).toBe(result);
  });

  it('drops a generated interface when a region declares a type alias of the same name', async () => {
    // Alias feedback: user replaced a generated interface with a hand-written
    // type alias inside a region. Region wins; no duplicate identifier.
    const existing = [
      header,
      '',
      '// @oagen-ignore-start',
      'export type CreateResponse = WireCreateResponse;',
      '// @oagen-ignore-end',
      '',
      'export interface WireCreateResponse {',
      '  id: string;',
      '}',
    ].join('\n');

    const generated = [
      header,
      '',
      'export interface CreateResponse {',
      '  id: string;',
      '}',
      '',
      'export interface WireCreateResponse {',
      '  id: string;',
      '}',
    ].join('\n');

    const result = await overwriteWithPreservedRegions(existing, generated, 'node');

    expect(result).not.toContain('export interface CreateResponse');
    expect(result).toContain('export type CreateResponse = WireCreateResponse;');
    const second = await overwriteWithPreservedRegions(result, generated, 'node');
    expect(second).toBe(result);
  });

  it('does not duplicate a const declared inside an ignore region', async () => {
    const existing = [
      header,
      '',
      '// @oagen-ignore-start',
      'export const DEFAULT_TIMEOUT = 30000;',
      '// @oagen-ignore-end',
      '',
      'export interface Other {',
      '  id: string;',
      '}',
    ].join('\n');

    const generated = [
      header,
      '',
      'export const DEFAULT_TIMEOUT = 5000;',
      '',
      'export interface Other {',
      '  id: string;',
      '}',
    ].join('\n');

    const result = await overwriteWithPreservedRegions(existing, generated, 'node');

    const count = (result.match(/^export const DEFAULT_TIMEOUT/gm) || []).length;
    expect(count).toBe(1);
    expect(result).toContain('30000');
    expect(result).not.toContain('5000');
    const second = await overwriteWithPreservedRegions(result, generated, 'node');
    expect(second).toBe(result);
  });

  it('does not duplicate a function declared inside an ignore region', async () => {
    const existing = [
      header,
      '',
      '// @oagen-ignore-start',
      'export function deserializeLink(data: unknown): string {',
      "  return 'custom';",
      '}',
      '// @oagen-ignore-end',
    ].join('\n');

    const generated = [
      header,
      '',
      'export function deserializeLink(data: unknown): string {',
      '  return String(data);',
      '}',
    ].join('\n');

    const result = await overwriteWithPreservedRegions(existing, generated, 'node');

    const count = (result.match(/^export function deserializeLink/gm) || []).length;
    expect(count).toBe(1);
    expect(result).toContain("'custom'");
    const second = await overwriteWithPreservedRegions(result, generated, 'node');
    expect(second).toBe(result);
  });

  it('still updates symbols not covered by any region', async () => {
    const existing = [
      header,
      '',
      '// @oagen-ignore-start',
      'export interface Protected {',
      '  custom: boolean;',
      '}',
      '// @oagen-ignore-end',
      '',
      'export interface Unprotected {',
      '  stale: string;',
      '}',
    ].join('\n');

    const generated = [
      header,
      '',
      'export interface Protected {',
      '  generatedField: string;',
      '}',
      '',
      'export interface Unprotected {',
      '  fresh: string;',
      '}',
    ].join('\n');

    const result = await overwriteWithPreservedRegions(existing, generated, 'node');

    // Region wins for the protected symbol
    expect(result).toContain('custom: boolean');
    expect(result).not.toContain('generatedField');
    // Unprotected symbol is fully regenerated (overwrite semantics)
    expect(result).toContain('fresh: string');
    expect(result).not.toContain('stale: string');
  });

  it('handles multiple regions protecting different declarations', async () => {
    const existing = [
      header,
      '',
      '// @oagen-ignore-start',
      'export interface First {',
      '  customA: boolean;',
      '}',
      '// @oagen-ignore-end',
      '',
      'export interface Middle {',
      '  id: string;',
      '}',
      '',
      '// @oagen-ignore-start',
      'export interface Last {',
      '  customB: boolean;',
      '}',
      '// @oagen-ignore-end',
    ].join('\n');

    const generated = [
      header,
      '',
      'export interface First {',
      '  a: string;',
      '}',
      '',
      'export interface Middle {',
      '  id: string;',
      '}',
      '',
      'export interface Last {',
      '  b: string;',
      '}',
    ].join('\n');

    const result = await overwriteWithPreservedRegions(existing, generated, 'node');

    expect((result.match(/^export interface First \{/gm) || []).length).toBe(1);
    expect((result.match(/^export interface Middle \{/gm) || []).length).toBe(1);
    expect((result.match(/^export interface Last \{/gm) || []).length).toBe(1);
    expect(result).toContain('customA: boolean');
    expect(result).toContain('customB: boolean');
    const second = await overwriteWithPreservedRegions(result, generated, 'node');
    expect(second).toBe(result);
  });

  it('handles a region at the end of the file', async () => {
    const existing = [
      header,
      '',
      'export interface Other {',
      '  id: string;',
      '}',
      '',
      '// @oagen-ignore-start',
      'export interface Trailing {',
      '  custom: boolean;',
      '}',
      '// @oagen-ignore-end',
    ].join('\n');

    const generated = [
      header,
      '',
      'export interface Other {',
      '  id: string;',
      '}',
      '',
      'export interface Trailing {',
      '  generated: string;',
      '}',
    ].join('\n');

    const result = await overwriteWithPreservedRegions(existing, generated, 'node');

    expect((result.match(/^export interface Trailing \{/gm) || []).length).toBe(1);
    expect(result).toContain('custom: boolean');
    expect(result).not.toContain('generated: string');
    const second = await overwriteWithPreservedRegions(result, generated, 'node');
    expect(second).toBe(result);
  });

  it('drops every generated duplicate when one region protects multiple declarations', async () => {
    const existing = [
      header,
      '',
      '// @oagen-ignore-start',
      'export interface GenerateLink {',
      '  customA: boolean;',
      '}',
      '',
      'export interface GenerateLinkResponse {',
      '  customB: boolean;',
      '}',
      '// @oagen-ignore-end',
    ].join('\n');

    const generated = [
      header,
      '',
      'export interface GenerateLink {',
      '  a: string;',
      '}',
      '',
      'export interface GenerateLinkResponse {',
      '  b: string;',
      '}',
    ].join('\n');

    const result = await overwriteWithPreservedRegions(existing, generated, 'node');

    expect((result.match(/^export interface GenerateLink \{/gm) || []).length).toBe(1);
    expect((result.match(/^export interface GenerateLinkResponse \{/gm) || []).length).toBe(1);
    expect(result).toContain('customA: boolean');
    expect(result).toContain('customB: boolean');
    const second = await overwriteWithPreservedRegions(result, generated, 'node');
    expect(second).toBe(result);
  });
});
