// This file is auto-generated by oagen. Do not edit.

import Foundation

/// Enumeration of valid OrganizationState values.
public enum OrganizationState: RawRepresentable, Codable, Sendable, Hashable {
    case active
    case inactive
    case pendingReview
    /// A value not known at SDK generation time.
    case unknown(String)

    public init(rawValue: String) {
        switch rawValue {
        case "active": self = .active
        case "inactive": self = .inactive
        case "pending_review": self = .pendingReview
        default: self = .unknown(rawValue)
        }
    }

    public var rawValue: String {
        switch self {
        case .active: return "active"
        case .inactive: return "inactive"
        case .pendingReview: return "pending_review"
        case .unknown(let value): return value
        }
    }

    public init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        self.init(rawValue: raw)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public static let allKnownCases: [OrganizationState] = [
        .active,
        .inactive,
        .pendingReview,
    ]
}
